insert into Airports (Name, Latitude, Longitude, City) values ('Mário Pereira Lopes–São Carlos', null, null, 'Weitang');
insert into Airports (Name, Latitude, Longitude, City) values ('Matsu Nangan Airport', null, null, 'Suqiaoxiang');
insert into Airports (Name, Latitude, Longitude, City) values ('Cherrabun Airport', null, null, 'Rio Claro');
insert into Airports (Name, Latitude, Longitude, City) values ('Virginia Airport', null, null, 'Porto Real');
insert into Airports (Name, Latitude, Longitude, City) values ('Antsirabe Airport', null, null, 'Nanyulinxi');
insert into Airports (Name, Latitude, Longitude, City) values ('Adana Airport', null, null, 'Miskolc');
insert into Airports (Name, Latitude, Longitude, City) values ('Pago Pago International Airpor', null, null, 'Shiqiaotou');
insert into Airports (Name, Latitude, Longitude, City) values ('Godthaab / Nuuk Airport', null, null, 'Xinghuo');
insert into Airports (Name, Latitude, Longitude, City) values ('Midland International Airport', null, null, 'Ottawa');
insert into Airports (Name, Latitude, Longitude, City) values ('Natuashish Airport', null, null, 'Lazaro Cardenas');
insert into Airports (Name, Latitude, Longitude, City) values ('Kawama Airport', null, null, 'Rubirizi');
insert into Airports (Name, Latitude, Longitude, City) values ('El Eden Airport', null, null, 'Preserje pri Radomljah');
insert into Airports (Name, Latitude, Longitude, City) values ('Djambala Airport', null, null, 'Nhơn Trạch');
insert into Airports (Name, Latitude, Longitude, City) values ('Dade Collier Training and Tran', null, null, 'Zhoutie');
insert into Airports (Name, Latitude, Longitude, City) values ('Qiemo Yudu Airport', null, null, 'Kizil');
insert into Airports (Name, Latitude, Longitude, City) values ('Sparrevohn LRRS Airport', null, null, 'Öldziyt');
insert into Airports (Name, Latitude, Longitude, City) values ('Wanaka Airport', null, null, 'Getafe');
insert into Airports (Name, Latitude, Longitude, City) values ('Vladivostok International Airp', null, null, 'Changgai');
insert into Airports (Name, Latitude, Longitude, City) values ('Stuart Island Airpark', null, null, 'Smoky Lake');
insert into Airports (Name, Latitude, Longitude, City) values ('Lolland Falster Maribo Airport', null, null, 'Lianozovo');
insert into Airports (Name, Latitude, Longitude, City) values ('Vopnafjörður Airport', null, null, 'Ganping');
insert into Airports (Name, Latitude, Longitude, City) values ('Coolah Airport', null, null, 'San Casimiro');
insert into Airports (Name, Latitude, Longitude, City) values ('Rzhevka Airport', null, null, 'Nankou');
insert into Airports (Name, Latitude, Longitude, City) values ('Dahl Creek Airport', null, null, 'Chartres');
insert into Airports (Name, Latitude, Longitude, City) values ('Asmara International Airport', null, null, 'Sławatycze');
insert into Airports (Name, Latitude, Longitude, City) values ('North Lakhimpur Airport', null, null, 'Mandalasari');
insert into Airports (Name, Latitude, Longitude, City) values ('Shoreham Airport', null, null, 'Mogwase');
insert into Airports (Name, Latitude, Longitude, City) values ('Havre City County Airport', null, null, 'Krasae Sin');
insert into Airports (Name, Latitude, Longitude, City) values ('Hutchinson County Airport', null, null, 'Vinhais');
insert into Airports (Name, Latitude, Longitude, City) values ('Ulanqab Jining Airport', null, null, 'Paris 15');
insert into Airports (Name, Latitude, Longitude, City) values ('Huntsville International Carl ', null, null, 'Itabaiana');
insert into Airports (Name, Latitude, Longitude, City) values ('Caquetania Airport', null, null, 'Oibioin');
insert into Airports (Name, Latitude, Longitude, City) values ('Fulton County Airport Brown Fi', null, null, 'Itiruçu');
insert into Airports (Name, Latitude, Longitude, City) values ('Sitiawan Airport', null, null, 'Kiên Lương');
insert into Airports (Name, Latitude, Longitude, City) values ('Scone Airport', null, null, 'Moorreesburg');
insert into Airports (Name, Latitude, Longitude, City) values ('Omak Airport', null, null, 'Tarxien');
insert into Airports (Name, Latitude, Longitude, City) values ('Ostend-Bruges International Ai', null, null, 'Villa de Soto');
insert into Airports (Name, Latitude, Longitude, City) values ('Sherbrooke Airport', null, null, 'Olocuilta');
insert into Airports (Name, Latitude, Longitude, City) values ('Nkongsamba Airport', null, null, 'Stratford');
insert into Airports (Name, Latitude, Longitude, City) values ('Blissville Airport', null, null, 'Youkaichi');
insert into Airports (Name, Latitude, Longitude, City) values ('Grand Cess Airport', null, null, 'Sannois');
insert into Airports (Name, Latitude, Longitude, City) values ('Wekweètì Airport', null, null, 'Anggana');
insert into Airports (Name, Latitude, Longitude, City) values ('Libo Airport', null, null, 'Welibo');
insert into Airports (Name, Latitude, Longitude, City) values ('Kaoma Airport', null, null, 'Pinhão');
insert into Airports (Name, Latitude, Longitude, City) values ('Algona Municipal Airport', null, null, 'Cihideung Satu');
insert into Airports (Name, Latitude, Longitude, City) values ('Île Art - Waala Airport', null, null, 'Eslāmābād');
insert into Airports (Name, Latitude, Longitude, City) values ('Casuarito Airport', null, null, 'Idi Rayeuk');
insert into Airports (Name, Latitude, Longitude, City) values ('Tol Airport', null, null, 'Onitsha');
insert into Airports (Name, Latitude, Longitude, City) values ('Muko Muko Airport', null, null, 'Murcia');
insert into Airports (Name, Latitude, Longitude, City) values ('Cholet Le Pontreau Airport', null, null, 'Cesson');
insert into Airports (Name, Latitude, Longitude, City) values ('Foula Airfield', null, null, 'Pamoyanan');
insert into Airports (Name, Latitude, Longitude, City) values ('Nairobi Wilson Airport', null, null, 'Xitieshan');
insert into Airports (Name, Latitude, Longitude, City) values ('Kasba Lake Airport', null, null, 'Kaabong');
insert into Airports (Name, Latitude, Longitude, City) values ('Montpellier-Méditerranée Airpo', null, null, 'Kalangan');
insert into Airports (Name, Latitude, Longitude, City) values ('Jorge Isaac Airport', null, null, 'Xindai');
insert into Airports (Name, Latitude, Longitude, City) values ('Yantai Laishan Airport', null, null, 'Zhangfang');
insert into Airports (Name, Latitude, Longitude, City) values ('Coeur D''Alene - Pappy Boyingto', null, null, 'Batibati');
insert into Airports (Name, Latitude, Longitude, City) values ('Blackwater Airport', null, null, 'Odienné');
insert into Airports (Name, Latitude, Longitude, City) values ('Conklin (Leismer) Airport', null, null, 'Kamyzyak');
insert into Airports (Name, Latitude, Longitude, City) values ('Sucua Airport', null, null, 'Maevatanana');
insert into Airports (Name, Latitude, Longitude, City) values ('Culberson County Airport', null, null, 'Lakhdenpokh’ya');
insert into Airports (Name, Latitude, Longitude, City) values ('Selfridge Air National Guard B', null, null, 'Kawaliwu');
insert into Airports (Name, Latitude, Longitude, City) values ('Moki Airport', null, null, 'Punta del Este');
insert into Airports (Name, Latitude, Longitude, City) values ('La Grande-4 Airport', null, null, 'Jatisari');
insert into Airports (Name, Latitude, Longitude, City) values ('Ouadda Airport', null, null, 'Karangbaru');
insert into Airports (Name, Latitude, Longitude, City) values ('Tuticorin Airport', null, null, 'Rozivka');
insert into Airports (Name, Latitude, Longitude, City) values ('Kirawira B Aerodrome', null, null, 'Zlatograd');
insert into Airports (Name, Latitude, Longitude, City) values ('Kos Airport', null, null, 'Néa Magnisía');
insert into Airports (Name, Latitude, Longitude, City) values ('Blissville Airport', null, null, 'San Carlos de Bolívar');
insert into Airports (Name, Latitude, Longitude, City) values ('Hatay Airport', null, null, 'Kotikawatta');
insert into Airports (Name, Latitude, Longitude, City) values ('Ratnagiri Airport', null, null, 'Oebaki');
insert into Airports (Name, Latitude, Longitude, City) values ('Okondja Airport', null, null, 'Sitrah');
insert into Airports (Name, Latitude, Longitude, City) values ('Nanga Pinoh Airport', null, null, 'Paris 14');
insert into Airports (Name, Latitude, Longitude, City) values ('Richard Toll Airport', null, null, 'Caticugan');
insert into Airports (Name, Latitude, Longitude, City) values ('Porto Seguro Airport', null, null, 'Oxelösund');
insert into Airports (Name, Latitude, Longitude, City) values ('Bollon Airport', null, null, 'Třebíč');
insert into Airports (Name, Latitude, Longitude, City) values ('Sertanópolis Airport', null, null, 'Saint-Eustache');
insert into Airports (Name, Latitude, Longitude, City) values ('Mount Etjo Airport', null, null, 'Igarra');
insert into Airports (Name, Latitude, Longitude, City) values ('Sandefjord Airport, Torp', null, null, 'Refojos');
insert into Airports (Name, Latitude, Longitude, City) values ('Zaraza Airport', null, null, 'Australia Square');
insert into Airports (Name, Latitude, Longitude, City) values ('Pirineus - la Seu d''Urgel Airp', null, null, 'Šalovci');
insert into Airports (Name, Latitude, Longitude, City) values ('Cowley Airport', null, null, 'Montpellier');
insert into Airports (Name, Latitude, Longitude, City) values ('Thompson Airport', null, null, 'Sakon Nakhon');
insert into Airports (Name, Latitude, Longitude, City) values ('Muir Army Air Field (Fort Indi', null, null, 'Sanjiang');
insert into Airports (Name, Latitude, Longitude, City) values ('Orán Airport', null, null, 'Chunshui');
insert into Airports (Name, Latitude, Longitude, City) values ('Richards Bay Airport', null, null, 'Tanjungrejo Lor');
insert into Airports (Name, Latitude, Longitude, City) values ('Timaru Airport', null, null, 'Takarazuka');
insert into Airports (Name, Latitude, Longitude, City) values ('Bahías de Huatulco Internation', null, null, 'Kokopo');
insert into Airports (Name, Latitude, Longitude, City) values ('Ellington Airport', null, null, 'Charlotte');
insert into Airports (Name, Latitude, Longitude, City) values ('Black Hills Airport-Clyde Ice ', null, null, 'Hats’avan');
insert into Airports (Name, Latitude, Longitude, City) values ('Punta Gorda Airport', null, null, 'Reims');
insert into Airports (Name, Latitude, Longitude, City) values ('Nelspruit Airport', null, null, 'Fengtai Chengguanzhen');
insert into Airports (Name, Latitude, Longitude, City) values ('Chernivtsi International Airpo', null, null, 'Dno');
insert into Airports (Name, Latitude, Longitude, City) values ('Forest City Municipal Airport', null, null, 'Pag');
insert into Airports (Name, Latitude, Longitude, City) values ('Cessna Aircraft Field', null, null, 'Çepan');
insert into Airports (Name, Latitude, Longitude, City) values ('Walcha Airport', null, null, 'Hněvotín');
insert into Airports (Name, Latitude, Longitude, City) values ('Sigonella Navy Air Base', null, null, 'Kidal');
insert into Airports (Name, Latitude, Longitude, City) values ('Key West International Airport', null, null, 'Södertälje');
insert into Airports (Name, Latitude, Longitude, City) values ('Oryol Yuzhny Airport', null, null, 'Yangji');
insert into Airports (Name, Latitude, Longitude, City) values ('Mannheim-City Airport', null, null, 'Fukumitsu');
insert into Airports (Name, Latitude, Longitude, City) values ('Grand Junction Regional Airpor', null, null, 'Colcabamba');
insert into Airports (Name, Latitude, Longitude, City) values ('Sur Airport', null, null, 'Tsagaanders');
insert into Airports (Name, Latitude, Longitude, City) values ('Gibb River Airport', null, null, 'Měřín');
insert into Airports (Name, Latitude, Longitude, City) values ('Wynyard Airport', null, null, 'Rongxing');
insert into Airports (Name, Latitude, Longitude, City) values ('Arso Airport', null, null, 'Longjing');
insert into Airports (Name, Latitude, Longitude, City) values ('El Petén Airport', null, null, 'Hua Hin');
insert into Airports (Name, Latitude, Longitude, City) values ('Warracknabeal Airport', null, null, 'Xiangtan');
insert into Airports (Name, Latitude, Longitude, City) values ('Kursk East Airport', null, null, 'Orléans');
insert into Airports (Name, Latitude, Longitude, City) values ('Libreville Leon M''ba Internati', null, null, 'Udënisht');
insert into Airports (Name, Latitude, Longitude, City) values ('Kulob Airport', null, null, 'Ningxin');
insert into Airports (Name, Latitude, Longitude, City) values ('El Recreo Airport', null, null, 'San Narciso');
insert into Airports (Name, Latitude, Longitude, City) values ('Diego Garcia Naval Support Fac', null, null, 'Lesnikovo');
insert into Airports (Name, Latitude, Longitude, City) values ('Orangeburg Municipal Airport', null, null, 'Zhishan');
insert into Airports (Name, Latitude, Longitude, City) values ('Iriona Airport', null, null, 'Luleå');
insert into Airports (Name, Latitude, Longitude, City) values ('Provo Municipal Airport', null, null, 'Springfield');
insert into Airports (Name, Latitude, Longitude, City) values ('University Park Airport', null, null, 'Lyon');
insert into Airports (Name, Latitude, Longitude, City) values ('Wakkanai Airport', null, null, 'Kosum Phisai');
insert into Airports (Name, Latitude, Longitude, City) values ('Devonport Airport', null, null, 'Gouménissa');
insert into Airports (Name, Latitude, Longitude, City) values ('Mytilene International Airport', null, null, 'Koynare');
insert into Airports (Name, Latitude, Longitude, City) values ('Kwigillingok Airport', null, null, 'Wuling');
insert into Airports (Name, Latitude, Longitude, City) values ('Burevestnik Airport', null, null, 'Cabiguan');
insert into Airports (Name, Latitude, Longitude, City) values ('Borba Airport', null, null, 'Tīkāpur');
insert into Airports (Name, Latitude, Longitude, City) values ('Casino Airport', null, null, 'Atiquizaya');
insert into Airports (Name, Latitude, Longitude, City) values ('Webster City Municipal Airport', null, null, 'Brańsk');
insert into Airports (Name, Latitude, Longitude, City) values ('Bazhong Enyang Airport', null, null, 'Ruilin');
insert into Airports (Name, Latitude, Longitude, City) values ('Holingol Huolinhe Airport', null, null, 'Sísion');
insert into Airports (Name, Latitude, Longitude, City) values ('Vivigani Airfield', null, null, 'Sacramento');
insert into Airports (Name, Latitude, Longitude, City) values ('Stevens Point Municipal Airpor', null, null, 'Huanshan');
insert into Airports (Name, Latitude, Longitude, City) values ('Hang Nadim International Airpo', null, null, 'Huwei');
insert into Airports (Name, Latitude, Longitude, City) values ('Paraparaumu Airport', null, null, 'Áno Merá');
insert into Airports (Name, Latitude, Longitude, City) values ('Belmonte Airport', null, null, 'Ekibastuz');
insert into Airports (Name, Latitude, Longitude, City) values ('Morobe Airport', null, null, 'Heiheba');
insert into Airports (Name, Latitude, Longitude, City) values ('Shaikh Zaid Airport', null, null, 'Purwokerto');
insert into Airports (Name, Latitude, Longitude, City) values ('Kipnuk Airport', null, null, 'Xiamazhuang');
insert into Airports (Name, Latitude, Longitude, City) values ('Lago Argentino Airport', null, null, 'Oguta');
insert into Airports (Name, Latitude, Longitude, City) values ('Gothenburg City Airport', null, null, 'Zapolyarnyy');
insert into Airports (Name, Latitude, Longitude, City) values ('Bunbury Airport', null, null, 'Bimbo');
insert into Airports (Name, Latitude, Longitude, City) values ('Ohrid St. Paul the Apostle Air', null, null, 'Maranura');
insert into Airports (Name, Latitude, Longitude, City) values ('Whatì Airport', null, null, 'Cilimus Kulon');
insert into Airports (Name, Latitude, Longitude, City) values ('Eskilstuna Airport', null, null, 'Huamu');
insert into Airports (Name, Latitude, Longitude, City) values ('General Leite de Castro Airpor', null, null, 'Welchman Hall');
insert into Airports (Name, Latitude, Longitude, City) values ('St George Airport', null, null, 'Tenjolaya');
insert into Airports (Name, Latitude, Longitude, City) values ('Arar Domestic Airport', null, null, 'Zhongzhang');
insert into Airports (Name, Latitude, Longitude, City) values ('Lyons-Rice County Municipal Ai', null, null, 'Besukrejo');
insert into Airports (Name, Latitude, Longitude, City) values ('Diapaga Airport', null, null, 'Sioguí Arriba');
insert into Airports (Name, Latitude, Longitude, City) values ('Moabi Airport', null, null, 'Ljungby');
insert into Airports (Name, Latitude, Longitude, City) values ('Telfer Airport', null, null, 'Ciriri');
insert into Airports (Name, Latitude, Longitude, City) values ('Dorobisoro Airport', null, null, 'Nancun');
insert into Airports (Name, Latitude, Longitude, City) values ('Manitowoc County Airport', null, null, 'Baguim do Monte');
insert into Airports (Name, Latitude, Longitude, City) values ('Jeongseok Airport', null, null, 'Mežica');
insert into Airports (Name, Latitude, Longitude, City) values ('Dothan Regional Airport', null, null, 'Jatiwangi');
insert into Airports (Name, Latitude, Longitude, City) values ('Mapua(Mabua) Airport', null, null, 'Putat Lor');
insert into Airports (Name, Latitude, Longitude, City) values ('Rundu Airport', null, null, 'Jambean');
insert into Airports (Name, Latitude, Longitude, City) values ('Whitesburg Municipal Airport', null, null, 'Buyuan');
insert into Airports (Name, Latitude, Longitude, City) values ('Pattaya Airpark', null, null, 'Radomir');
insert into Airports (Name, Latitude, Longitude, City) values ('Tanga Airport', null, null, 'Milíkov');
insert into Airports (Name, Latitude, Longitude, City) values ('Paros National Airport', null, null, 'Iraquara');
insert into Airports (Name, Latitude, Longitude, City) values ('Mafia Island Airport', null, null, 'Zhangaqorghan');
insert into Airports (Name, Latitude, Longitude, City) values ('Pope Field', null, null, 'Dikwa');
insert into Airports (Name, Latitude, Longitude, City) values ('Okha Airport', null, null, 'Hŭngju-dong');
insert into Airports (Name, Latitude, Longitude, City) values ('Rokot Airport', null, null, 'Paris 16');
insert into Airports (Name, Latitude, Longitude, City) values ('Taitung Airport', null, null, 'Grabów');
insert into Airports (Name, Latitude, Longitude, City) values ('Lashio Airport', null, null, 'Labé');
insert into Airports (Name, Latitude, Longitude, City) values ('Dewadaru - Kemujan Island', null, null, 'Luzhou');
insert into Airports (Name, Latitude, Longitude, City) values ('Klagenfurt Airport', null, null, 'Novais');
insert into Airports (Name, Latitude, Longitude, City) values ('Thomas C Russell Field', null, null, 'Netrakona');
insert into Airports (Name, Latitude, Longitude, City) values ('Neil Armstrong Airport', null, null, 'Donglai');
insert into Airports (Name, Latitude, Longitude, City) values ('Ejin Banner-Taolai Airport', null, null, 'Laoag');
insert into Airports (Name, Latitude, Longitude, City) values ('Vahitahi Airport', null, null, 'Huddinge');
insert into Airports (Name, Latitude, Longitude, City) values ('Green River Municipal Airport', null, null, 'Kabor');
insert into Airports (Name, Latitude, Longitude, City) values ('Amata Airport', null, null, 'Loma Bonita');
insert into Airports (Name, Latitude, Longitude, City) values ('Provincetown Municipal Airport', null, null, 'Engenheiro Beltrão');
insert into Airports (Name, Latitude, Longitude, City) values ('Camp Bastion Airport', null, null, 'Severnyy');
insert into Airports (Name, Latitude, Longitude, City) values ('Kadanwari Airport', null, null, 'Wilanagara');
insert into Airports (Name, Latitude, Longitude, City) values ('Futuna Airport', null, null, 'Smålandsstenar');
insert into Airports (Name, Latitude, Longitude, City) values ('Worland Municipal Airport', null, null, 'Karangduren Dua');
insert into Airports (Name, Latitude, Longitude, City) values ('Kandep Airport', null, null, 'Ignacio Zaragoza');
insert into Airports (Name, Latitude, Longitude, City) values ('Tonghua Sanyuanpu Airport', null, null, 'Binitayan');
insert into Airports (Name, Latitude, Longitude, City) values ('Nulato Airport', null, null, 'Raniżów');
insert into Airports (Name, Latitude, Longitude, City) values ('Nulato Airport', null, null, 'Camp Ithier');
insert into Airports (Name, Latitude, Longitude, City) values ('Jackson Hole Airport', null, null, 'Solkan');
insert into Airports (Name, Latitude, Longitude, City) values ('Pellston Regional Airport of E', null, null, 'Catarman');
insert into Airports (Name, Latitude, Longitude, City) values ('Alto Molocue Airport', null, null, 'Kholbon');
insert into Airports (Name, Latitude, Longitude, City) values ('Tongren Fenghuang Airport', null, null, 'Munturkaju');
insert into Airports (Name, Latitude, Longitude, City) values ('Fairview Airport', null, null, 'Helsingborg');
insert into Airports (Name, Latitude, Longitude, City) values ('Platinum Airport', null, null, 'Zouérat');
insert into Airports (Name, Latitude, Longitude, City) values ('Rae Lakes Airport', null, null, 'Zhongxing');
insert into Airports (Name, Latitude, Longitude, City) values ('Stord Airport', null, null, 'Yanyang');
insert into Airports (Name, Latitude, Longitude, City) values ('Dong Hoi Airport', null, null, 'Datun');
insert into Airports (Name, Latitude, Longitude, City) values ('Show Low Regional Airport', null, null, 'Gubu');
insert into Airports (Name, Latitude, Longitude, City) values ('Tupelo Regional Airport', null, null, 'Qarah Bāgh');
insert into Airports (Name, Latitude, Longitude, City) values ('Tri-County Regional Airport', null, null, 'Dolo');
insert into Airports (Name, Latitude, Longitude, City) values ('Kandahar Airport', null, null, 'Lyon');
insert into Airports (Name, Latitude, Longitude, City) values ('Seward Airport', null, null, 'Chom Bueng');
insert into Airports (Name, Latitude, Longitude, City) values ('Nikunau Airport', null, null, 'Bonik');
insert into Airports (Name, Latitude, Longitude, City) values ('Qacha''s Nek Airport', null, null, 'Makrýgialos');
insert into Airports (Name, Latitude, Longitude, City) values ('Aur Island Airport', null, null, 'Otradnoye');
insert into Airports (Name, Latitude, Longitude, City) values ('Ilimanaq Heliport', null, null, 'Seogeom-ri');
insert into Airports (Name, Latitude, Longitude, City) values ('Dr. Babasaheb Ambedkar Interna', null, null, 'Canmang');
insert into Airports (Name, Latitude, Longitude, City) values ('Waris Airport', null, null, 'Sukasetia');
insert into Airports (Name, Latitude, Longitude, City) values ('Heriberto Gíl Martínez Airport', null, null, 'Jeblog Satu');
insert into Airports (Name, Latitude, Longitude, City) values ('Port Hedland International Air', null, null, 'Golomunta');
insert into Airports (Name, Latitude, Longitude, City) values ('Palacios Airport', null, null, 'Puspajaya');
insert into Airports (Name, Latitude, Longitude, City) values ('Usiminas Airport', null, null, 'Guantang');
insert into Airports (Name, Latitude, Longitude, City) values ('Yancheng Airport', null, null, 'Sanxi');
insert into Airports (Name, Latitude, Longitude, City) values ('Pagadian Airport', null, null, 'Grängesberg');
insert into Airports (Name, Latitude, Longitude, City) values ('Andre Maggi Airport', null, null, 'Canghou');
insert into Airports (Name, Latitude, Longitude, City) values ('Las Américas International Air', null, null, 'Storozhevaya');
insert into Airports (Name, Latitude, Longitude, City) values ('Iowa Falls Municipal Airport', null, null, 'Trajouce');
insert into Airports (Name, Latitude, Longitude, City) values ('San Juan Del César Airport', null, null, 'Louiseville');
insert into Airports (Name, Latitude, Longitude, City) values ('Wonken Airport', null, null, 'Shyroke');
insert into Airports (Name, Latitude, Longitude, City) values ('Atar International Airport', null, null, 'Santa Bárbara');
insert into Airports (Name, Latitude, Longitude, City) values ('Alicante International Airport', null, null, 'Kuala Terengganu');
insert into Airports (Name, Latitude, Longitude, City) values ('Huntsville International Carl ', null, null, 'Murcia');
insert into Airports (Name, Latitude, Longitude, City) values ('Long Sukang Airport', null, null, 'Cemplang');
insert into Airports (Name, Latitude, Longitude, City) values ('Poplar Hill Airport', null, null, 'Sawangan');
insert into Airports (Name, Latitude, Longitude, City) values ('Charlo Airport', null, null, 'Ejigbo');
insert into Airports (Name, Latitude, Longitude, City) values ('Varna Airport', null, null, 'Tiemen');
insert into Airports (Name, Latitude, Longitude, City) values ('Gary Chicago International Air', null, null, 'Namyangju');
insert into Airports (Name, Latitude, Longitude, City) values ('Brunette Downs Airport', null, null, 'Burmakino');
insert into Airports (Name, Latitude, Longitude, City) values ('Palm Beach County Glades Airpo', null, null, 'Shuicha');
insert into Airports (Name, Latitude, Longitude, City) values ('Kota Airport', null, null, 'Montluçon');
insert into Airports (Name, Latitude, Longitude, City) values ('Tulcea Airport', null, null, 'New Cebu');
insert into Airports (Name, Latitude, Longitude, City) values ('Gütersloh Air Base', null, null, 'Shtip');
insert into Airports (Name, Latitude, Longitude, City) values ('Coventry Airport', null, null, 'Neuilly-sur-Seine');
insert into Airports (Name, Latitude, Longitude, City) values ('Dangriga Airport', null, null, 'Huangbei');
insert into Airports (Name, Latitude, Longitude, City) values ('Bagram Air Base', null, null, 'Famaillá');
insert into Airports (Name, Latitude, Longitude, City) values ('Sur Airport', null, null, 'Kuanheum');
insert into Airports (Name, Latitude, Longitude, City) values ('Atka Airport', null, null, 'Jaú');
insert into Airports (Name, Latitude, Longitude, City) values ('Hanimaadhoo Airport', null, null, 'La Curva');
insert into Airports (Name, Latitude, Longitude, City) values ('Yengema Airport', null, null, 'Ndewel');
insert into Airports (Name, Latitude, Longitude, City) values ('Redhill Aerodrome', null, null, 'Parys');
insert into Airports (Name, Latitude, Longitude, City) values ('Redhill Aerodrome', null, null, 'Pensacola');
insert into Airports (Name, Latitude, Longitude, City) values ('Guararapes - Gilberto Freyre I', null, null, 'Taiping');
insert into Airports (Name, Latitude, Longitude, City) values ('Pagadian Airport', null, null, 'Měřín');
insert into Airports (Name, Latitude, Longitude, City) values ('Ingalls Field', null, null, 'Sioguí Arriba');
insert into Airports (Name, Latitude, Longitude, City) values ('Girua Airport', null, null, 'Purral');
insert into Airports (Name, Latitude, Longitude, City) values ('Kwethluk Airport', null, null, 'Yeşilköy');
insert into Airports (Name, Latitude, Longitude, City) values ('Campo Mourão Airport', null, null, 'Shahe');
insert into Airports (Name, Latitude, Longitude, City) values ('Soldotna Airport', null, null, 'Wete');
insert into Airports (Name, Latitude, Longitude, City) values ('Peter O Knight Airport', null, null, 'Aguitu');
insert into Airports (Name, Latitude, Longitude, City) values ('Condobolin Airport', null, null, 'Surkhet');
insert into Airports (Name, Latitude, Longitude, City) values ('Yorketown Airport', null, null, 'Zhamog');
insert into Airports (Name, Latitude, Longitude, City) values ('Songea Airport', null, null, 'Soi Dao');
insert into Airports (Name, Latitude, Longitude, City) values ('Albert J Ellis Airport', null, null, 'Jiaze');
insert into Airports (Name, Latitude, Longitude, City) values ('Agropecuária Castanhais Airpor', null, null, 'Homa Bay');
insert into Airports (Name, Latitude, Longitude, City) values ('Touho Airport', null, null, 'Courtaboeuf');
insert into Airports (Name, Latitude, Longitude, City) values ('San Nicolas De Bari Airport', null, null, 'Jiguaní');
insert into Airports (Name, Latitude, Longitude, City) values ('Watsonville Municipal Airport', null, null, 'Rychnov nad Kněžnou');
insert into Airports (Name, Latitude, Longitude, City) values ('Ukhta Airport', null, null, 'Bamban');
insert into Airports (Name, Latitude, Longitude, City) values ('Los Cerrillos Airport', null, null, 'Chiang Yuen');
insert into Airports (Name, Latitude, Longitude, City) values ('Orlando Executive Airport', null, null, 'Dom Pedrito');
insert into Airports (Name, Latitude, Longitude, City) values ('Pacific City State Airport', null, null, 'Yayva');
insert into Airports (Name, Latitude, Longitude, City) values ('Tocumen International Airport', null, null, 'Himeville');
insert into Airports (Name, Latitude, Longitude, City) values ('Bluefields Airport', null, null, 'Fátima');
insert into Airports (Name, Latitude, Longitude, City) values ('Bergen Airport Flesland', null, null, 'Cikadondongdesa');
insert into Airports (Name, Latitude, Longitude, City) values ('Nizhnevartovsk Airport', null, null, 'Gandra');
insert into Airports (Name, Latitude, Longitude, City) values ('Marsa Alam International Airpo', null, null, 'Soukkouma');
insert into Airports (Name, Latitude, Longitude, City) values ('Halliburton Field', null, null, 'Newark');
insert into Airports (Name, Latitude, Longitude, City) values ('Licenciado Gustavo Díaz Ordaz ', null, null, 'Bagangan');
insert into Airports (Name, Latitude, Longitude, City) values ('Powell River Airport', null, null, 'Palca');
insert into Airports (Name, Latitude, Longitude, City) values ('Woodie Woodie Airport', null, null, 'Sleman');
insert into Airports (Name, Latitude, Longitude, City) values ('São Pedro Airport', null, null, 'Pincher Creek');
insert into Airports (Name, Latitude, Longitude, City) values ('Lupin Airport', null, null, 'Binawara');
insert into Airports (Name, Latitude, Longitude, City) values ('Leme Airport', null, null, 'Rio Claro');
insert into Airports (Name, Latitude, Longitude, City) values ('Castellón-Costa Azahar Airport', null, null, 'Zawichost');
insert into Airports (Name, Latitude, Longitude, City) values ('Ålesund Airport', null, null, 'Luna');
insert into Airports (Name, Latitude, Longitude, City) values ('Licenciado Benito Juarez Inter', null, null, 'Višňova');
insert into Airports (Name, Latitude, Longitude, City) values ('Abel Santamaria Airport', null, null, 'Granada');
insert into Airports (Name, Latitude, Longitude, City) values ('Kuito Airport', null, null, 'Sinŭiju');
insert into Airports (Name, Latitude, Longitude, City) values ('Lago Argentino Airport', null, null, 'Pocokan Satu');
insert into Airports (Name, Latitude, Longitude, City) values ('Laguna Army Airfield', null, null, 'Kyaikkami');
insert into Airports (Name, Latitude, Longitude, City) values ('Lokpriya Gopinath Bordoloi Int', null, null, 'Wiset Chaichan');
insert into Airports (Name, Latitude, Longitude, City) values ('Saravane Airport', null, null, 'Granada');
insert into Airports (Name, Latitude, Longitude, City) values ('Red Devil Airport', null, null, 'Pingshanhu');
insert into Airports (Name, Latitude, Longitude, City) values ('Eilat Airport', null, null, 'Kavarna');
insert into Airports (Name, Latitude, Longitude, City) values ('Fazenda Barra do Agudo Airport', null, null, 'Svenljunga');
insert into Airports (Name, Latitude, Longitude, City) values ('Pimenta Bueno Airport', null, null, 'La Paz');
insert into Airports (Name, Latitude, Longitude, City) values ('Ha''il Airport', null, null, 'Buan');
insert into Airports (Name, Latitude, Longitude, City) values ('Xieng Khouang Airport', null, null, 'Monjarás');
insert into Airports (Name, Latitude, Longitude, City) values ('Fond du Lac County Airport', null, null, 'Heshe');
insert into Airports (Name, Latitude, Longitude, City) values ('Phitsanulok Airport', null, null, 'Kotsyubyns’ke');
insert into Airports (Name, Latitude, Longitude, City) values ('La Chinita International Airpo', null, null, 'Faleula');
insert into Airports (Name, Latitude, Longitude, City) values ('Boryspil International Airport', null, null, 'Oenam');
insert into Airports (Name, Latitude, Longitude, City) values ('Gray Army Air Field', null, null, 'Bontang');
insert into Airports (Name, Latitude, Longitude, City) values ('Almirante Padilla Airport', null, null, 'Xiangshan');
insert into Airports (Name, Latitude, Longitude, City) values ('Aqaba King Hussein Internation', null, null, 'Xintian');
insert into Airports (Name, Latitude, Longitude, City) values ('Ryan''s Creek Aerodrome', null, null, 'Mambalan');
insert into Airports (Name, Latitude, Longitude, City) values ('Ames Municipal Airport', null, null, 'Qobu');
insert into Airports (Name, Latitude, Longitude, City) values ('Port Meadville Airport', null, null, 'Jundiaí');
insert into Airports (Name, Latitude, Longitude, City) values ('Tinboli Airport', null, null, 'Itapetinga');
insert into Airports (Name, Latitude, Longitude, City) values ('Conklin (Leismer) Airport', null, null, 'Pilníkov');
insert into Airports (Name, Latitude, Longitude, City) values ('Inus Airport', null, null, 'London');
insert into Airports (Name, Latitude, Longitude, City) values ('Garoua International Airport', null, null, 'Shimodate');
insert into Airports (Name, Latitude, Longitude, City) values ('Whiteriver Airport', null, null, 'Dawang');
insert into Airports (Name, Latitude, Longitude, City) values ('Middle Georgia Regional Airpor', null, null, 'Lens');
insert into Airports (Name, Latitude, Longitude, City) values ('Magas Airport', null, null, 'Načeradec');
insert into Airports (Name, Latitude, Longitude, City) values ('Sauce Viejo Airport', null, null, 'Um Jar Al Gharbiyya');
insert into Airports (Name, Latitude, Longitude, City) values ('Talkeetna Airport', null, null, 'Villejuif');
insert into Airports (Name, Latitude, Longitude, City) values ('Houma Terrebonne Airport', null, null, 'Chenda');
insert into Airports (Name, Latitude, Longitude, City) values ('Dakhla Airport', null, null, 'Ambat');
insert into Airports (Name, Latitude, Longitude, City) values ('Queen Beatrix International Ai', null, null, 'Kroya');
insert into Airports (Name, Latitude, Longitude, City) values ('Seoul Air Base (K-16)', null, null, 'Huskvarna');
insert into Airports (Name, Latitude, Longitude, City) values ('Jabiru Airport', null, null, 'Dayuanhuizu');
insert into Airports (Name, Latitude, Longitude, City) values ('Aosta Airport', null, null, 'Jiangxiangzhen');
insert into Airports (Name, Latitude, Longitude, City) values ('Deadman''s Cay Airport', null, null, 'Xujiadian');
insert into Airports (Name, Latitude, Longitude, City) values ('Kissimmee Gateway Airport', null, null, 'Helmas');
insert into Airports (Name, Latitude, Longitude, City) values ('Pauk Airport', null, null, 'Sidi Smaïl');
insert into Airports (Name, Latitude, Longitude, City) values ('Vologda Airport', null, null, 'Peñarrubia');
insert into Airports (Name, Latitude, Longitude, City) values ('Cliff Hatfield Memorial Airpor', null, null, 'Lanling');
insert into Airports (Name, Latitude, Longitude, City) values ('Bern Belp Airport', null, null, 'Chaihu');
insert into Airports (Name, Latitude, Longitude, City) values ('Odense Airport', null, null, 'Albuquerque');
insert into Airports (Name, Latitude, Longitude, City) values ('Semonkong Airport', null, null, 'Ulluaya');
insert into Airports (Name, Latitude, Longitude, City) values ('Kimmirut Airport', null, null, 'Badarganj');
insert into Airports (Name, Latitude, Longitude, City) values ('El Nido Airport', null, null, 'Zhaobei');
insert into Airports (Name, Latitude, Longitude, City) values ('Yecheon Airbase', null, null, 'Danirai');
insert into Airports (Name, Latitude, Longitude, City) values ('Eilat Airport', null, null, 'Pameungpeuk');
insert into Airports (Name, Latitude, Longitude, City) values ('Bearskin Lake Airport', null, null, 'Santa Maria');
insert into Airports (Name, Latitude, Longitude, City) values ('Sundsvall-Härnösand Airport', null, null, 'Aţ Ţīrah');
insert into Airports (Name, Latitude, Longitude, City) values ('Barreirinhas Airport', null, null, 'Kez');
insert into Airports (Name, Latitude, Longitude, City) values ('Angoon Seaplane Base', null, null, 'Nyimba');
insert into Airports (Name, Latitude, Longitude, City) values ('Lekhwair Airport', null, null, 'Shinpokh');
insert into Airports (Name, Latitude, Longitude, City) values ('NASA Crows Landing Airport', null, null, 'Anilao');
insert into Airports (Name, Latitude, Longitude, City) values ('Presidente Nicolau Lobato Inte', null, null, 'Łobżenica');
insert into Airports (Name, Latitude, Longitude, City) values ('Karshi Khanabad Airport', null, null, 'Jianyi');
insert into Airports (Name, Latitude, Longitude, City) values ('Diamantina Lakes Airport', null, null, 'Bianzhuang');
insert into Airports (Name, Latitude, Longitude, City) values ('Sitkinak Airport', null, null, 'Sal’sk');
insert into Airports (Name, Latitude, Longitude, City) values ('Münster Osnabrück Airport', null, null, 'Coromandel');
insert into Airports (Name, Latitude, Longitude, City) values ('Daşoguz Airport', null, null, 'Jieshi');
insert into Airports (Name, Latitude, Longitude, City) values ('Nkongsamba Airport', null, null, 'Aramayuan');
insert into Airports (Name, Latitude, Longitude, City) values ('Aneityum Airport', null, null, 'Krasnoye');
insert into Airports (Name, Latitude, Longitude, City) values ('Kericho Airport', null, null, 'Wonokerto');
insert into Airports (Name, Latitude, Longitude, City) values ('Bassel Al-Assad International ', null, null, 'Zhangqiang');
insert into Airports (Name, Latitude, Longitude, City) values ('Vernal Regional Airport', null, null, 'San Antonio');
insert into Airports (Name, Latitude, Longitude, City) values ('Lugano Airport', null, null, 'Luuka Town');
insert into Airports (Name, Latitude, Longitude, City) values ('Hudiksvall Airport', null, null, 'Changchuan');
insert into Airports (Name, Latitude, Longitude, City) values ('Betoota Airport', null, null, 'Khawr Maksar');
insert into Airports (Name, Latitude, Longitude, City) values ('Bria Airport', null, null, 'Washington');
insert into Airports (Name, Latitude, Longitude, City) values ('Natadola Airport', null, null, 'Baleagung');
insert into Airports (Name, Latitude, Longitude, City) values ('Abilene Regional Airport', null, null, 'Lárdos');
insert into Airports (Name, Latitude, Longitude, City) values ('Santa Maria Airport', null, null, 'Sigou');
insert into Airports (Name, Latitude, Longitude, City) values ('Rivers Airport', null, null, 'Portland');
insert into Airports (Name, Latitude, Longitude, City) values ('Wemindji Airport', null, null, 'Ágios Efstrátios');
insert into Airports (Name, Latitude, Longitude, City) values ('London Stansted Airport', null, null, 'Villa Yapacaní');
insert into Airports (Name, Latitude, Longitude, City) values ('Nioki Airport', null, null, 'Örgön');
insert into Airports (Name, Latitude, Longitude, City) values ('Kirsch Municipal Airport', null, null, 'Yelat’ma');
insert into Airports (Name, Latitude, Longitude, City) values ('General Servando Canales Inter', null, null, 'Cuozheqiangma');
insert into Airports (Name, Latitude, Longitude, City) values ('Fakahina Airport', null, null, 'Phatthalung');
insert into Airports (Name, Latitude, Longitude, City) values ('Cacique Aramare Airport', null, null, 'Oslo');
insert into Airports (Name, Latitude, Longitude, City) values ('Dinwiddie County Airport', null, null, 'Weiyang');
insert into Airports (Name, Latitude, Longitude, City) values ('Pyay Airport', null, null, 'Sunduk');
insert into Airports (Name, Latitude, Longitude, City) values ('Tarapaina Airport', null, null, 'Tegalbuleud');
insert into Airports (Name, Latitude, Longitude, City) values ('La Chorrera Airport', null, null, 'Angasmarca');
insert into Airports (Name, Latitude, Longitude, City) values ('Renmark Airport', null, null, 'Carquefou');
insert into Airports (Name, Latitude, Longitude, City) values ('Glendale Fokker Field', null, null, 'Angol');
insert into Airports (Name, Latitude, Longitude, City) values ('Héroes De Malvinas Airport', null, null, 'Martaban');
insert into Airports (Name, Latitude, Longitude, City) values ('Kiev Zhuliany International Ai', null, null, 'Magetlegar');
insert into Airports (Name, Latitude, Longitude, City) values ('Cesar Lim Rodriguez Airport', null, null, 'Tongquan');
insert into Airports (Name, Latitude, Longitude, City) values ('General Manuel Serrano Airport', null, null, 'Bassano');
insert into Airports (Name, Latitude, Longitude, City) values ('Diapaga Airport', null, null, 'Muyi');
insert into Airports (Name, Latitude, Longitude, City) values ('NAS Fort Worth JRB/Carswell Fi', null, null, 'Hengli');
insert into Airports (Name, Latitude, Longitude, City) values ('Lese Airport', null, null, 'Kungsbacka');
insert into Airports (Name, Latitude, Longitude, City) values ('Gral. Bernardo O´Higgins Airpo', null, null, 'Ribeira');
insert into Airports (Name, Latitude, Longitude, City) values ('Lusambo Airport', null, null, 'Staryy Saltiv');
insert into Airports (Name, Latitude, Longitude, City) values ('Vilo Acuña International Airpo', null, null, 'Hamberang Sabrang');
insert into Airports (Name, Latitude, Longitude, City) values ('Ashland Municipal Sumner Parke', null, null, 'Qianxu Zhen');
insert into Airports (Name, Latitude, Longitude, City) values ('Lauro Carneiro de Loyola Airpo', null, null, 'Huabeitun');
insert into Airports (Name, Latitude, Longitude, City) values ('Coastal Carolina Regional Airp', null, null, 'Cértegui');
insert into Airports (Name, Latitude, Longitude, City) values ('Pico Airport', null, null, 'Palaiseau');
insert into Airports (Name, Latitude, Longitude, City) values ('Mariupol International Airport', null, null, 'Cabatang');
insert into Airports (Name, Latitude, Longitude, City) values ('Munbil Airport', null, null, 'Ketawang');
insert into Airports (Name, Latitude, Longitude, City) values ('Bantry Aerodrome', null, null, 'Luzino');
insert into Airports (Name, Latitude, Longitude, City) values ('Kebar Airport', null, null, 'Ashgabat');
insert into Airports (Name, Latitude, Longitude, City) values ('Benson Municipal Airport', null, null, 'Morteros');
insert into Airports (Name, Latitude, Longitude, City) values ('Sharm El Sheikh International ', null, null, 'Tala');
insert into Airports (Name, Latitude, Longitude, City) values ('Presidente José Sarney Airport', null, null, 'Ḩadīdah');
insert into Airports (Name, Latitude, Longitude, City) values ('Khabarovsk-Novy Airport', null, null, 'Maogou');
insert into Airports (Name, Latitude, Longitude, City) values ('Ventspils International Airpor', null, null, 'San Lucas Sacatepéquez');
insert into Airports (Name, Latitude, Longitude, City) values ('Porterville Municipal Airport', null, null, 'Banqiao');
insert into Airports (Name, Latitude, Longitude, City) values ('Elenak Airport', null, null, 'Yueyang');
insert into Airports (Name, Latitude, Longitude, City) values ('Namsang Airport', null, null, 'Paris 11');
insert into Airports (Name, Latitude, Longitude, City) values ('Ivano-Frankivsk International ', null, null, 'Santa Rosa de Aguán');
insert into Airports (Name, Latitude, Longitude, City) values ('Catalão Airport', null, null, 'Balyqshy');
insert into Airports (Name, Latitude, Longitude, City) values ('Kelanoa Airport', null, null, 'Baturaja');
insert into Airports (Name, Latitude, Longitude, City) values ('German Olano Airport', null, null, 'Tongouson');
insert into Airports (Name, Latitude, Longitude, City) values ('Velikiye Luki Airport', null, null, 'Quinocay');
insert into Airports (Name, Latitude, Longitude, City) values ('El Nido Airport', null, null, 'Sukorejo');
insert into Airports (Name, Latitude, Longitude, City) values ('Fuzhou Changle International A', null, null, 'Carcassonne');
insert into Airports (Name, Latitude, Longitude, City) values ('Tumut Airport', null, null, 'Jinchang');
insert into Airports (Name, Latitude, Longitude, City) values ('Karlovy Vary International Air', null, null, 'Ramalhal');
insert into Airports (Name, Latitude, Longitude, City) values ('Kurgan Airport', null, null, 'Kobiernice');
insert into Airports (Name, Latitude, Longitude, City) values ('Quincy Regional Baldwin Field', null, null, 'Oslo');
insert into Airports (Name, Latitude, Longitude, City) values ('Christiansted Harbor Seaplane ', null, null, 'Koksovyy');
insert into Airports (Name, Latitude, Longitude, City) values ('Nenana Municipal Airport', null, null, 'Brak');
insert into Airports (Name, Latitude, Longitude, City) values ('Tucupita Airport', null, null, 'Ryjewo');
insert into Airports (Name, Latitude, Longitude, City) values ('Totness Airport', null, null, 'Muurame');
insert into Airports (Name, Latitude, Longitude, City) values ('Ngau Airport', null, null, 'Bjästa');
insert into Airports (Name, Latitude, Longitude, City) values ('Pinto Martins International Ai', null, null, 'Sacotes');
insert into Airports (Name, Latitude, Longitude, City) values ('Astana International Airport', null, null, 'Al ‘Awjah');
insert into Airports (Name, Latitude, Longitude, City) values ('Presidente Juscelino Kubistsch', null, null, 'Fraile Pintado');
insert into Airports (Name, Latitude, Longitude, City) values ('Sullivan Bay Seaplane Base', null, null, 'Velké Hoštice');
insert into Airports (Name, Latitude, Longitude, City) values ('Puerto Lempira Airport', null, null, 'Jianjiang');
insert into Airports (Name, Latitude, Longitude, City) values ('South Bimini Airport', null, null, 'Sterling');
insert into Airports (Name, Latitude, Longitude, City) values ('Almirante Marco Andres Zar Air', null, null, 'Västerås');
insert into Airports (Name, Latitude, Longitude, City) values ('Rock Hill - York County Airpor', null, null, 'Lolayan');
insert into Airports (Name, Latitude, Longitude, City) values ('Capital International Airport', null, null, 'Nantes');
insert into Airports (Name, Latitude, Longitude, City) values ('Phillips Army Air Field', null, null, 'Baiba');
insert into Airports (Name, Latitude, Longitude, City) values ('Meyers Chuck Seaplane Base', null, null, 'Simeykyne');
insert into Airports (Name, Latitude, Longitude, City) values ('Xavantina Airport', null, null, 'Lerrnanist');
insert into Airports (Name, Latitude, Longitude, City) values ('Bahia Piña Airport', null, null, 'Brodek u Přerova');
insert into Airports (Name, Latitude, Longitude, City) values ('Mannheim-City Airport', null, null, 'Zhuyang');
insert into Airports (Name, Latitude, Longitude, City) values ('Koulamoutou Mabimbi Airport', null, null, 'Carcar');
insert into Airports (Name, Latitude, Longitude, City) values ('Hobart International Airport', null, null, 'Aizi');
insert into Airports (Name, Latitude, Longitude, City) values ('Andrés Miguel Salazar Marcano ', null, null, 'Gongli');
insert into Airports (Name, Latitude, Longitude, City) values ('Wotje Atoll Airport', null, null, 'Laotai');
insert into Airports (Name, Latitude, Longitude, City) values ('Coronel E Carvajal Airport', null, null, 'São Sebastião do Paraíso');
insert into Airports (Name, Latitude, Longitude, City) values ('Toussus-le-Noble Airport', null, null, 'Tonghae');
insert into Airports (Name, Latitude, Longitude, City) values ('Macomb Municipal Airport', null, null, 'Minanga Norte');
insert into Airports (Name, Latitude, Longitude, City) values ('Edwards Air Force Base', null, null, 'Guiset East');
insert into Airports (Name, Latitude, Longitude, City) values ('Sultan Abdul Halim Airport', null, null, 'Balekambang');
insert into Airports (Name, Latitude, Longitude, City) values ('Fitzroy Crossing Airport', null, null, 'Bukbatang');
insert into Airports (Name, Latitude, Longitude, City) values ('Oneida County Airport', null, null, 'Hai’an');
insert into Airports (Name, Latitude, Longitude, City) values ('Rokot Airport', null, null, 'Arboleda');
insert into Airports (Name, Latitude, Longitude, City) values ('Braga Municipal Aerodrome', null, null, 'Falāvarjān');
insert into Airports (Name, Latitude, Longitude, City) values ('Stokmarknes Skagen Airport', null, null, 'Hezuoqiao');
insert into Airports (Name, Latitude, Longitude, City) values ('Puerto La Victoria Airport', null, null, 'Dourbali');
insert into Airports (Name, Latitude, Longitude, City) values ('Mkambati Airport', null, null, 'Lyubymivka');
insert into Airports (Name, Latitude, Longitude, City) values ('Stuart Island Airstrip', null, null, 'Lipa City');
insert into Airports (Name, Latitude, Longitude, City) values ('Barter Island LRRS Airport', null, null, 'Boyarka');
insert into Airports (Name, Latitude, Longitude, City) values ('Algona Municipal Airport', null, null, 'Choisy-le-Roi');
insert into Airports (Name, Latitude, Longitude, City) values ('Charlotte Douglas Internationa', null, null, 'Tatsuno');
insert into Airports (Name, Latitude, Longitude, City) values ('Dalnerechensk Airport', null, null, 'Tumba');
insert into Airports (Name, Latitude, Longitude, City) values ('Unalaska Airport', null, null, 'Xigangzi');
insert into Airports (Name, Latitude, Longitude, City) values ('Rif Airport', null, null, 'Shar');
insert into Airports (Name, Latitude, Longitude, City) values ('Elk City Regional Business Air', null, null, 'Vyshneve');
insert into Airports (Name, Latitude, Longitude, City) values ('Cakung Airport', null, null, 'Jindong');
insert into Airports (Name, Latitude, Longitude, City) values ('Villa Reynolds Airport', null, null, 'Kuty');
insert into Airports (Name, Latitude, Longitude, City) values ('Comodoro D.R. Salomón Airport', null, null, 'Maloarkhangel’sk');
insert into Airports (Name, Latitude, Longitude, City) values ('Iosco County Airport', null, null, 'Veruela');
insert into Airports (Name, Latitude, Longitude, City) values ('Bishop International Airport', null, null, 'Gambarjati');
insert into Airports (Name, Latitude, Longitude, City) values ('Castro Airport', null, null, 'Zhizhong');
insert into Airports (Name, Latitude, Longitude, City) values ('Pune Airport', null, null, 'Fuji');
insert into Airports (Name, Latitude, Longitude, City) values ('Punta Chivato Airport', null, null, 'Tongxing');
insert into Airports (Name, Latitude, Longitude, City) values ('Kogalym International Airport', null, null, 'Älvsjö');
insert into Airports (Name, Latitude, Longitude, City) values ('Maitland Airport', null, null, 'Duqiong');
insert into Airports (Name, Latitude, Longitude, City) values ('Industrial Airpark', null, null, 'Gnieżdżewo');
insert into Airports (Name, Latitude, Longitude, City) values ('North Perry Airport', null, null, 'Quintães');
insert into Airports (Name, Latitude, Longitude, City) values ('Serafin Enoss Bertaso Airport', null, null, 'Ystad');
insert into Airports (Name, Latitude, Longitude, City) values ('Chignik Lake Airport', null, null, 'Carrasqueira');
insert into Airports (Name, Latitude, Longitude, City) values ('Poços de Caldas - Embaixador W', null, null, 'Ecroignard');
insert into Airports (Name, Latitude, Longitude, City) values ('Patrocínio Airport', null, null, 'Kitami');
insert into Airports (Name, Latitude, Longitude, City) values ('Inukjuak Airport', null, null, 'Ruokolahti');
insert into Airports (Name, Latitude, Longitude, City) values ('Iğdır Airport', null, null, 'Komsomolsk');
insert into Airports (Name, Latitude, Longitude, City) values ('Bandırma Airport', null, null, 'Tangqian');
insert into Airports (Name, Latitude, Longitude, City) values ('Block Island State Airport', null, null, 'Codrington');
insert into Airports (Name, Latitude, Longitude, City) values ('Darchula Airport', null, null, 'Petro-Slavyanka');
insert into Airports (Name, Latitude, Longitude, City) values ('Eniwetok Airport', null, null, 'Barreiro do Jaíba');
insert into Airports (Name, Latitude, Longitude, City) values ('Matthews Ridge Airport', null, null, 'Jinjing');
insert into Airports (Name, Latitude, Longitude, City) values ('Licenciado Manuel Crescencio R', null, null, 'Al Balyanā');
insert into Airports (Name, Latitude, Longitude, City) values ('Khowai Airport', null, null, 'Warnes');
insert into Airports (Name, Latitude, Longitude, City) values ('Colonia Catriel Airport', null, null, 'Marcq-en-Barœul');
insert into Airports (Name, Latitude, Longitude, City) values ('Portland Airport', null, null, 'Mae Hi');
insert into Airports (Name, Latitude, Longitude, City) values ('Broadus Airport', null, null, 'Bureya');
insert into Airports (Name, Latitude, Longitude, City) values ('Birmingham-Shuttlesworth Inter', null, null, 'Niquinohomo');
insert into Airports (Name, Latitude, Longitude, City) values ('Hawkins Field', null, null, 'Årjäng');
insert into Airports (Name, Latitude, Longitude, City) values ('Council Bluffs Municipal Airpo', null, null, 'Krajan Caluk');
insert into Airports (Name, Latitude, Longitude, City) values ('Terrell Municipal Airport', null, null, 'Tumba');
insert into Airports (Name, Latitude, Longitude, City) values ('Clovis Municipal Airport', null, null, 'Bantiran');
insert into Airports (Name, Latitude, Longitude, City) values ('Mbala Airport', null, null, 'Viekšniai');
insert into Airports (Name, Latitude, Longitude, City) values ('Ross River Airport', null, null, 'Belén Gualcho');
insert into Airports (Name, Latitude, Longitude, City) values ('Dios Airport', null, null, 'Khilok');
insert into Airports (Name, Latitude, Longitude, City) values ('Woodbourne Airport', null, null, 'Lombo Meão');
insert into Airports (Name, Latitude, Longitude, City) values ('Santana do Araguaia Airport', null, null, 'Watublapi');
insert into Airports (Name, Latitude, Longitude, City) values ('Williams Lake Airport', null, null, 'Kota Kinabalu');
insert into Airports (Name, Latitude, Longitude, City) values ('RAF Benson', null, null, 'Rujewa');
insert into Airports (Name, Latitude, Longitude, City) values ('Drake Bay Airport', null, null, 'Clondalkin');
insert into Airports (Name, Latitude, Longitude, City) values ('Niquelândia Airport', null, null, 'Nanao');
insert into Airports (Name, Latitude, Longitude, City) values ('Mohammed V International Airpo', null, null, 'Tangxi');
insert into Airports (Name, Latitude, Longitude, City) values ('Spriggs Payne Airport', null, null, 'Sungairaya');
insert into Airports (Name, Latitude, Longitude, City) values ('Montpellier-Méditerranée Airpo', null, null, 'Antsohihy');
insert into Airports (Name, Latitude, Longitude, City) values ('Ocala International Airport - ', null, null, 'Galubakul');
insert into Airports (Name, Latitude, Longitude, City) values ('Naoro Airport', null, null, 'Gaotang');
insert into Airports (Name, Latitude, Longitude, City) values ('Béchar Boudghene Ben Ali Lotfi', null, null, 'Nagrog');
insert into Airports (Name, Latitude, Longitude, City) values ('Merritt Airport', null, null, 'Sidomulyo');
insert into Airports (Name, Latitude, Longitude, City) values ('Strezhevoy Airport', null, null, 'Wairiang');
insert into Airports (Name, Latitude, Longitude, City) values ('Hawkins Field', null, null, 'Oklahoma City');
insert into Airports (Name, Latitude, Longitude, City) values ('Gascoyne Junction Airport', null, null, 'Ágio Pnévma');
insert into Airports (Name, Latitude, Longitude, City) values ('Antlers Municipal Airport', null, null, 'Papetoai');
insert into Airports (Name, Latitude, Longitude, City) values ('Mangalore International Airpor', null, null, 'Jiulong');
insert into Airports (Name, Latitude, Longitude, City) values ('Angel Fire Airport', null, null, 'Al Mughayyir');
insert into Airports (Name, Latitude, Longitude, City) values ('Henderson Field', null, null, 'Gent');
insert into Airports (Name, Latitude, Longitude, City) values ('Hearst René Fontaine Municipal', null, null, 'Tanlad');
insert into Airports (Name, Latitude, Longitude, City) values ('Maiduguri International Airpor', null, null, 'Nagornyy');
insert into Airports (Name, Latitude, Longitude, City) values ('York Airport', null, null, 'Monkey Hill');
insert into Airports (Name, Latitude, Longitude, City) values ('Zinder Airport', null, null, 'Sugiharjo');
insert into Airports (Name, Latitude, Longitude, City) values ('Muttaburra Airport', null, null, 'Huacrachuco');
insert into Airports (Name, Latitude, Longitude, City) values ('Teller Airport', null, null, 'Alavus');
insert into Airports (Name, Latitude, Longitude, City) values ('Nanga Pinoh Airport', null, null, 'Jiefang');
insert into Airports (Name, Latitude, Longitude, City) values ('Palmas del Mar Airstrip', null, null, 'Pasararba');
insert into Airports (Name, Latitude, Longitude, City) values ('Ercan International Airport', null, null, 'Kushk');
