insert into Cards (grade, review) values (5, 'holistic');
insert into Cards (grade, review) values (6, 'Streamlined');
insert into Cards (grade, review) values (9, 'Optimized');
insert into Cards (grade, review) values (4, 'architecture');
insert into Cards (grade, review) values (1, 'Switchable');
insert into Cards (grade, review) values (7, 'mission-critical');
insert into Cards (grade, review) values (9, 'Innovative');
insert into Cards (grade, review) values (3, 'Digitized');
insert into Cards (grade, review) values (1, 'incremental');
insert into Cards (grade, review) values (7, 'local area network');
insert into Cards (grade, review) values (5, 'success');
insert into Cards (grade, review) values (6, 'firmware');
insert into Cards (grade, review) values (5, 'Multi-layered');
insert into Cards (grade, review) values (7, 'Exclusive');
insert into Cards (grade, review) values (3, 'multi-tasking');
insert into Cards (grade, review) values (6, 'Compatible');
insert into Cards (grade, review) values (7, 'mission-critical');
insert into Cards (grade, review) values (1, 'methodology');
insert into Cards (grade, review) values (9, 'Vision-oriented');
insert into Cards (grade, review) values (1, 'alliance');
insert into Cards (grade, review) values (7, 'Digitized');
insert into Cards (grade, review) values (8, 'Persevering');
insert into Cards (grade, review) values (8, '3rd generation');
insert into Cards (grade, review) values (3, 'fresh-thinking');
insert into Cards (grade, review) values (9, 'website');
insert into Cards (grade, review) values (1, 'Synergized');
insert into Cards (grade, review) values (10, 'clear-thinking');
insert into Cards (grade, review) values (8, 'Synergistic');
insert into Cards (grade, review) values (1, 'Universal');
insert into Cards (grade, review) values (6, 'eco-centric');
insert into Cards (grade, review) values (1, 'intranet');
insert into Cards (grade, review) values (10, 'didactic');
insert into Cards (grade, review) values (8, 'context-sensitive');
insert into Cards (grade, review) values (1, 'architecture');
insert into Cards (grade, review) values (4, 'Business-focused');
insert into Cards (grade, review) values (1, 'database');
insert into Cards (grade, review) values (10, 'client-driven');
insert into Cards (grade, review) values (1, 'conglomeration');
insert into Cards (grade, review) values (3, 'initiative');
insert into Cards (grade, review) values (7, 'Sharable');
insert into Cards (grade, review) values (10, 'Organized');
insert into Cards (grade, review) values (6, 'circuit');
insert into Cards (grade, review) values (10, 'Ameliorated');
insert into Cards (grade, review) values (5, 'uniform');
insert into Cards (grade, review) values (1, 'matrices');
insert into Cards (grade, review) values (6, 'access');
insert into Cards (grade, review) values (3, 'global');
insert into Cards (grade, review) values (1, 'analyzing');
insert into Cards (grade, review) values (3, 'client-driven');
insert into Cards (grade, review) values (4, 'Ameliorated');
insert into Cards (grade, review) values (8, 'Open-architected');
insert into Cards (grade, review) values (2, 'national');
insert into Cards (grade, review) values (9, 'framework');
insert into Cards (grade, review) values (3, 'bifurcated');
insert into Cards (grade, review) values (1, 'product');
insert into Cards (grade, review) values (9, 'data-warehouse');
insert into Cards (grade, review) values (8, 'dedicated');
insert into Cards (grade, review) values (10, 'Multi-lateral');
insert into Cards (grade, review) values (8, '3rd generation');
insert into Cards (grade, review) values (10, 'system-worthy');
insert into Cards (grade, review) values (6, 'global');
insert into Cards (grade, review) values (1, 'application');
insert into Cards (grade, review) values (5, 'Compatible');
insert into Cards (grade, review) values (4, 'exuding');
insert into Cards (grade, review) values (1, 'Down-sized');
insert into Cards (grade, review) values (10, 'Self-enabling');
insert into Cards (grade, review) values (10, 'incremental');
insert into Cards (grade, review) values (9, 'solution');
insert into Cards (grade, review) values (4, 'needs-based');
insert into Cards (grade, review) values (6, 'empowering');
insert into Cards (grade, review) values (10, 'Secured');
insert into Cards (grade, review) values (4, 'Automated');
insert into Cards (grade, review) values (9, 'Vision-oriented');
insert into Cards (grade, review) values (6, 'concept');
insert into Cards (grade, review) values (5, 'Sharable');
insert into Cards (grade, review) values (7, 'non-volatile');
insert into Cards (grade, review) values (8, 'tangible');
insert into Cards (grade, review) values (2, '6th generation');
insert into Cards (grade, review) values (3, 'contextually-based');
insert into Cards (grade, review) values (6, 'Multi-lateral');
insert into Cards (grade, review) values (5, 'project');
insert into Cards (grade, review) values (2, 'optimizing');
insert into Cards (grade, review) values (3, 'bottom-line');
insert into Cards (grade, review) values (5, 'complexity');
insert into Cards (grade, review) values (9, 'Monitored');
insert into Cards (grade, review) values (3, 'Customizable');
insert into Cards (grade, review) values (9, 'dynamic');
insert into Cards (grade, review) values (3, 'discrete');
insert into Cards (grade, review) values (10, 'utilisation');
insert into Cards (grade, review) values (4, 'contextually-based');
insert into Cards (grade, review) values (8, 'Pre-emptive');
insert into Cards (grade, review) values (8, 'optimizing');
insert into Cards (grade, review) values (2, 'Robust');
insert into Cards (grade, review) values (8, 'executive');
insert into Cards (grade, review) values (6, 'approach');
insert into Cards (grade, review) values (8, 'Fully-configurable');
insert into Cards (grade, review) values (9, 'reciprocal');
insert into Cards (grade, review) values (2, 'content-based');
insert into Cards (grade, review) values (8, 'Multi-channelled');
insert into Cards (grade, review) values (1, 'scalable');
insert into Cards (grade, review) values (6, 'logistical');
insert into Cards (grade, review) values (10, 'human-resource');
insert into Cards (grade, review) values (1, 'Triple-buffered');
insert into Cards (grade, review) values (4, 'explicit');
insert into Cards (grade, review) values (4, 'next generation');
insert into Cards (grade, review) values (4, 'adapter');
insert into Cards (grade, review) values (1, 'mobile');
insert into Cards (grade, review) values (1, 'Down-sized');
insert into Cards (grade, review) values (1, 'monitoring');
insert into Cards (grade, review) values (5, 'Cross-platform');
insert into Cards (grade, review) values (7, 'hub');
insert into Cards (grade, review) values (9, 'Configurable');
insert into Cards (grade, review) values (3, 'instruction set');
insert into Cards (grade, review) values (5, 'Total');
insert into Cards (grade, review) values (10, 'toolset');
insert into Cards (grade, review) values (8, 'systemic');
insert into Cards (grade, review) values (8, 'model');
insert into Cards (grade, review) values (10, 'content-based');
insert into Cards (grade, review) values (6, 'analyzing');
insert into Cards (grade, review) values (3, 'Polarised');
insert into Cards (grade, review) values (2, 'local');
insert into Cards (grade, review) values (8, 'discrete');
insert into Cards (grade, review) values (1, 'asynchronous');
insert into Cards (grade, review) values (10, 'infrastructure');
insert into Cards (grade, review) values (6, 'Enterprise-wide');
insert into Cards (grade, review) values (10, 'system engine');
insert into Cards (grade, review) values (7, 'system engine');
insert into Cards (grade, review) values (7, 'radical');
insert into Cards (grade, review) values (2, 'Multi-layered');
insert into Cards (grade, review) values (7, 'website');
insert into Cards (grade, review) values (3, 'Advanced');
insert into Cards (grade, review) values (7, 'info-mediaries');
insert into Cards (grade, review) values (6, 'definition');
insert into Cards (grade, review) values (8, 'Integrated');
insert into Cards (grade, review) values (5, 'fresh-thinking');
insert into Cards (grade, review) values (2, 'intranet');
insert into Cards (grade, review) values (7, 'Total');
insert into Cards (grade, review) values (9, 'open architecture');
insert into Cards (grade, review) values (1, 'multi-tasking');
insert into Cards (grade, review) values (1, 'protocol');
insert into Cards (grade, review) values (4, 'leverage');
insert into Cards (grade, review) values (3, 'system engine');
insert into Cards (grade, review) values (5, 'implementation');
insert into Cards (grade, review) values (1, 'optimal');
insert into Cards (grade, review) values (3, 'Grass-roots');
insert into Cards (grade, review) values (5, 'Sharable');
insert into Cards (grade, review) values (2, 'definition');
insert into Cards (grade, review) values (8, 'protocol');
insert into Cards (grade, review) values (2, 'attitude');
insert into Cards (grade, review) values (9, 'Object-based');
insert into Cards (grade, review) values (5, 'Object-based');
insert into Cards (grade, review) values (9, 'Streamlined');
insert into Cards (grade, review) values (9, 'Visionary');
insert into Cards (grade, review) values (9, 'open architecture');
insert into Cards (grade, review) values (2, 'Customer-focused');
insert into Cards (grade, review) values (6, '4th generation');
insert into Cards (grade, review) values (7, 'Realigned');
insert into Cards (grade, review) values (5, 'Monitored');
insert into Cards (grade, review) values (3, 'non-volatile');
insert into Cards (grade, review) values (4, 'Reactive');
insert into Cards (grade, review) values (8, 'Assimilated');
insert into Cards (grade, review) values (3, 'tertiary');
insert into Cards (grade, review) values (3, 'Implemented');
insert into Cards (grade, review) values (9, 'Diverse');
insert into Cards (grade, review) values (5, 'forecast');
insert into Cards (grade, review) values (8, 'local area network');
insert into Cards (grade, review) values (6, 'tertiary');
insert into Cards (grade, review) values (10, 'knowledge base');
insert into Cards (grade, review) values (1, '24 hour');
insert into Cards (grade, review) values (8, 'superstructure');
insert into Cards (grade, review) values (8, 'framework');
insert into Cards (grade, review) values (10, 'Managed');
insert into Cards (grade, review) values (9, 'homogeneous');
insert into Cards (grade, review) values (6, 'project');
insert into Cards (grade, review) values (10, 'project');
insert into Cards (grade, review) values (4, 'user-facing');
insert into Cards (grade, review) values (4, 'bifurcated');
insert into Cards (grade, review) values (7, 'capability');
insert into Cards (grade, review) values (10, 'help-desk');
insert into Cards (grade, review) values (9, 'Multi-layered');
insert into Cards (grade, review) values (7, 'Optimized');
insert into Cards (grade, review) values (3, 'Automated');
insert into Cards (grade, review) values (7, 'toolset');
insert into Cards (grade, review) values (6, 'Stand-alone');
insert into Cards (grade, review) values (9, 'Universal');
insert into Cards (grade, review) values (10, 'Integrated');
insert into Cards (grade, review) values (1, 'instruction set');
insert into Cards (grade, review) values (10, 'pricing structure');
insert into Cards (grade, review) values (7, 'Advanced');
insert into Cards (grade, review) values (5, 'access');
insert into Cards (grade, review) values (4, 'homogeneous');
insert into Cards (grade, review) values (4, 'leading edge');
insert into Cards (grade, review) values (7, 'web-enabled');
insert into Cards (grade, review) values (3, 'open architecture');
insert into Cards (grade, review) values (4, 'initiative');
insert into Cards (grade, review) values (4, 'encompassing');
insert into Cards (grade, review) values (9, 'Re-engineered');
insert into Cards (grade, review) values (10, 'Optimized');
insert into Cards (grade, review) values (6, 'internet solution');
insert into Cards (grade, review) values (6, 'benchmark');
insert into Cards (grade, review) values (2, 'Up-sized');
insert into Cards (grade, review) values (3, '5th generation');
insert into Cards (grade, review) values (3, 'encoding');
insert into Cards (grade, review) values (2, 'leverage');
insert into Cards (grade, review) values (3, 'definition');
insert into Cards (grade, review) values (2, 'Multi-layered');
insert into Cards (grade, review) values (6, 'mobile');
insert into Cards (grade, review) values (4, 'encoding');
insert into Cards (grade, review) values (1, 'ability');
insert into Cards (grade, review) values (7, 'grid-enabled');
insert into Cards (grade, review) values (7, 'Visionary');
insert into Cards (grade, review) values (5, 'database');
insert into Cards (grade, review) values (10, 'installation');
insert into Cards (grade, review) values (6, 'bifurcated');
insert into Cards (grade, review) values (5, 'tangible');
insert into Cards (grade, review) values (6, 'instruction set');
insert into Cards (grade, review) values (10, 'function');
insert into Cards (grade, review) values (3, 'radical');
insert into Cards (grade, review) values (4, 'Graphic Interface');
insert into Cards (grade, review) values (8, 'secured line');
insert into Cards (grade, review) values (9, 'frame');
insert into Cards (grade, review) values (4, 'Up-sized');
insert into Cards (grade, review) values (8, 'clear-thinking');
insert into Cards (grade, review) values (8, 'empowering');
insert into Cards (grade, review) values (10, 'Upgradable');
insert into Cards (grade, review) values (2, 'Re-contextualized');
insert into Cards (grade, review) values (10, 'Graphic Interface');
insert into Cards (grade, review) values (5, 'exuding');
insert into Cards (grade, review) values (9, 'Fully-configurable');
insert into Cards (grade, review) values (4, 'Focused');
insert into Cards (grade, review) values (1, 'hardware');
insert into Cards (grade, review) values (7, 'Profit-focused');
insert into Cards (grade, review) values (4, 'archive');
insert into Cards (grade, review) values (6, 'Universal');
insert into Cards (grade, review) values (2, 'homogeneous');
insert into Cards (grade, review) values (10, 'flexibility');
insert into Cards (grade, review) values (7, 'Switchable');
insert into Cards (grade, review) values (1, 'task-force');
insert into Cards (grade, review) values (1, 'challenge');
insert into Cards (grade, review) values (3, 'Virtual');
insert into Cards (grade, review) values (1, 'internet solution');
insert into Cards (grade, review) values (8, 'Seamless');
insert into Cards (grade, review) values (6, 'moratorium');
insert into Cards (grade, review) values (8, 'eco-centric');
insert into Cards (grade, review) values (7, 'clear-thinking');
insert into Cards (grade, review) values (10, 'asynchronous');
insert into Cards (grade, review) values (9, 'Multi-channelled');
insert into Cards (grade, review) values (4, 'attitude-oriented');
insert into Cards (grade, review) values (6, 'Profound');
insert into Cards (grade, review) values (2, 'info-mediaries');
insert into Cards (grade, review) values (6, 'Optional');
insert into Cards (grade, review) values (4, 'Multi-channelled');
insert into Cards (grade, review) values (10, 'function');
insert into Cards (grade, review) values (3, 'fresh-thinking');
insert into Cards (grade, review) values (10, 'well-modulated');
insert into Cards (grade, review) values (10, 'Total');
insert into Cards (grade, review) values (2, 'strategy');
insert into Cards (grade, review) values (4, 'complexity');
insert into Cards (grade, review) values (3, 'impactful');
insert into Cards (grade, review) values (7, 'knowledge base');
insert into Cards (grade, review) values (4, 'attitude-oriented');
insert into Cards (grade, review) values (6, 'circuit');
insert into Cards (grade, review) values (7, 'Innovative');
insert into Cards (grade, review) values (5, 'heuristic');
insert into Cards (grade, review) values (7, 'multimedia');
insert into Cards (grade, review) values (6, 'budgetary management');
insert into Cards (grade, review) values (10, 'neutral');
insert into Cards (grade, review) values (2, 'support');
insert into Cards (grade, review) values (3, 'model');
insert into Cards (grade, review) values (6, 'Exclusive');
insert into Cards (grade, review) values (5, 'hub');
insert into Cards (grade, review) values (10, 'interface');
insert into Cards (grade, review) values (1, 'Switchable');
insert into Cards (grade, review) values (6, 'budgetary management');
insert into Cards (grade, review) values (9, 'Robust');
insert into Cards (grade, review) values (10, 'foreground');
insert into Cards (grade, review) values (10, 'Ameliorated');
insert into Cards (grade, review) values (8, 'solution');
insert into Cards (grade, review) values (8, 'Multi-tiered');
insert into Cards (grade, review) values (8, 'Visionary');
insert into Cards (grade, review) values (4, 'encryption');
insert into Cards (grade, review) values (9, 'responsive');
insert into Cards (grade, review) values (2, 'Fully-configurable');
insert into Cards (grade, review) values (8, '5th generation');
insert into Cards (grade, review) values (6, 'Re-engineered');
insert into Cards (grade, review) values (2, 'Organic');
insert into Cards (grade, review) values (2, 'Cross-platform');
insert into Cards (grade, review) values (5, 'bifurcated');
insert into Cards (grade, review) values (3, 'info-mediaries');
insert into Cards (grade, review) values (10, 'Streamlined');
insert into Cards (grade, review) values (6, 'budgetary management');
insert into Cards (grade, review) values (10, 'impactful');
insert into Cards (grade, review) values (2, 'throughput');
insert into Cards (grade, review) values (7, 'multi-state');
insert into Cards (grade, review) values (6, 'Decentralized');
insert into Cards (grade, review) values (7, 'array');
insert into Cards (grade, review) values (6, 'Programmable');
insert into Cards (grade, review) values (8, 'challenge');
insert into Cards (grade, review) values (8, 'Synergized');
insert into Cards (grade, review) values (10, 'application');
insert into Cards (grade, review) values (5, 'time-frame');
insert into Cards (grade, review) values (2, 'Digitized');
insert into Cards (grade, review) values (8, 'regional');
insert into Cards (grade, review) values (8, 'Focused');
insert into Cards (grade, review) values (5, 'data-warehouse');
insert into Cards (grade, review) values (2, 'multimedia');
insert into Cards (grade, review) values (1, 'Persevering');
insert into Cards (grade, review) values (4, 'Right-sized');
insert into Cards (grade, review) values (6, 'leverage');
insert into Cards (grade, review) values (5, 'maximized');
insert into Cards (grade, review) values (2, 'Team-oriented');
insert into Cards (grade, review) values (2, 'contextually-based');
insert into Cards (grade, review) values (8, 'Phased');
insert into Cards (grade, review) values (7, 'Graphical User Interface');
insert into Cards (grade, review) values (2, 'software');
insert into Cards (grade, review) values (1, 'Multi-lateral');
insert into Cards (grade, review) values (6, 'Polarised');
insert into Cards (grade, review) values (1, 'customer loyalty');
insert into Cards (grade, review) values (6, 'secondary');
insert into Cards (grade, review) values (6, 'Persevering');
insert into Cards (grade, review) values (2, 'standardization');
insert into Cards (grade, review) values (3, 'global');
insert into Cards (grade, review) values (3, 'alliance');
insert into Cards (grade, review) values (5, 'middleware');
insert into Cards (grade, review) values (8, 'Ameliorated');
insert into Cards (grade, review) values (1, 'interface');
insert into Cards (grade, review) values (7, 'global');
insert into Cards (grade, review) values (5, 'knowledge user');
insert into Cards (grade, review) values (2, 'Graphical User Interface');
insert into Cards (grade, review) values (4, 'contingency');
insert into Cards (grade, review) values (9, 'adapter');
insert into Cards (grade, review) values (9, '24 hour');
insert into Cards (grade, review) values (5, 'Cross-group');
insert into Cards (grade, review) values (9, 'secured line');
insert into Cards (grade, review) values (8, 'orchestration');
insert into Cards (grade, review) values (4, '3rd generation');
insert into Cards (grade, review) values (2, 'bandwidth-monitored');
insert into Cards (grade, review) values (6, 'info-mediaries');
insert into Cards (grade, review) values (9, 'motivating');
insert into Cards (grade, review) values (5, 'executive');
insert into Cards (grade, review) values (5, 'bifurcated');
insert into Cards (grade, review) values (5, 'Enterprise-wide');
insert into Cards (grade, review) values (9, 'software');
insert into Cards (grade, review) values (7, 'non-volatile');
insert into Cards (grade, review) values (8, 'time-frame');
insert into Cards (grade, review) values (9, 'scalable');
insert into Cards (grade, review) values (7, 'database');
insert into Cards (grade, review) values (8, 'Triple-buffered');
insert into Cards (grade, review) values (9, 'alliance');
insert into Cards (grade, review) values (4, 'zero defect');
insert into Cards (grade, review) values (6, 'Progressive');
insert into Cards (grade, review) values (3, 'Customer-focused');
insert into Cards (grade, review) values (8, 'Devolved');
insert into Cards (grade, review) values (4, 'analyzing');
insert into Cards (grade, review) values (6, 'encryption');
insert into Cards (grade, review) values (8, 'value-added');
insert into Cards (grade, review) values (10, 'Down-sized');
insert into Cards (grade, review) values (2, 'Progressive');
insert into Cards (grade, review) values (10, 'leading edge');
insert into Cards (grade, review) values (7, 'background');
insert into Cards (grade, review) values (1, 'intangible');
insert into Cards (grade, review) values (1, 'Down-sized');
insert into Cards (grade, review) values (6, 'web-enabled');
insert into Cards (grade, review) values (3, 'array');
insert into Cards (grade, review) values (10, 'transitional');
insert into Cards (grade, review) values (2, 'groupware');
insert into Cards (grade, review) values (10, 'Balanced');
insert into Cards (grade, review) values (6, 'Enterprise-wide');
insert into Cards (grade, review) values (5, 'knowledge base');
insert into Cards (grade, review) values (10, 'Public-key');
insert into Cards (grade, review) values (1, 'Function-based');
insert into Cards (grade, review) values (10, 'even-keeled');
insert into Cards (grade, review) values (10, 'analyzer');
insert into Cards (grade, review) values (3, 'Managed');
insert into Cards (grade, review) values (2, 'Versatile');
insert into Cards (grade, review) values (8, 'pricing structure');
insert into Cards (grade, review) values (4, 'interface');
insert into Cards (grade, review) values (5, 'knowledge base');
insert into Cards (grade, review) values (10, 'Adaptive');
insert into Cards (grade, review) values (6, 'functionalities');
insert into Cards (grade, review) values (6, 'Exclusive');
insert into Cards (grade, review) values (1, 'infrastructure');
insert into Cards (grade, review) values (2, 'monitoring');
insert into Cards (grade, review) values (4, 'fresh-thinking');
insert into Cards (grade, review) values (8, 'policy');
insert into Cards (grade, review) values (7, 'Extended');
insert into Cards (grade, review) values (6, 'utilisation');
insert into Cards (grade, review) values (1, 'Graphical User Interface');
insert into Cards (grade, review) values (8, 'concept');
insert into Cards (grade, review) values (8, 'non-volatile');
insert into Cards (grade, review) values (6, 'Virtual');
insert into Cards (grade, review) values (5, 'orchestration');
insert into Cards (grade, review) values (8, 'De-engineered');
insert into Cards (grade, review) values (8, 'circuit');
insert into Cards (grade, review) values (3, 'function');
insert into Cards (grade, review) values (8, 'synergy');
insert into Cards (grade, review) values (8, 'structure');
insert into Cards (grade, review) values (5, 'info-mediaries');
insert into Cards (grade, review) values (8, 'throughput');
insert into Cards (grade, review) values (1, 'protocol');
insert into Cards (grade, review) values (4, 'fault-tolerant');
insert into Cards (grade, review) values (2, 'next generation');
insert into Cards (grade, review) values (3, 'mission-critical');
insert into Cards (grade, review) values (8, 'Profound');
insert into Cards (grade, review) values (7, 'composite');
insert into Cards (grade, review) values (9, 'Self-enabling');
insert into Cards (grade, review) values (4, 'multi-tasking');
insert into Cards (grade, review) values (3, 'Innovative');
insert into Cards (grade, review) values (7, 'regional');
insert into Cards (grade, review) values (8, 'hardware');
insert into Cards (grade, review) values (1, 'Upgradable');
insert into Cards (grade, review) values (7, 'Enhanced');
insert into Cards (grade, review) values (9, 'Monitored');
insert into Cards (grade, review) values (8, 'fresh-thinking');
insert into Cards (grade, review) values (3, 'Multi-lateral');
insert into Cards (grade, review) values (2, 'middleware');
insert into Cards (grade, review) values (2, 'Programmable');
insert into Cards (grade, review) values (5, 'explicit');
insert into Cards (grade, review) values (10, 'frame');
insert into Cards (grade, review) values (6, 'human-resource');
insert into Cards (grade, review) values (4, 'Synchronised');
insert into Cards (grade, review) values (8, 'system engine');
insert into Cards (grade, review) values (10, 'well-modulated');
insert into Cards (grade, review) values (8, 'optimal');
insert into Cards (grade, review) values (4, 'Focused');
insert into Cards (grade, review) values (2, 'conglomeration');
insert into Cards (grade, review) values (10, 'neutral');
insert into Cards (grade, review) values (9, 'object-oriented');
insert into Cards (grade, review) values (4, 'architecture');
insert into Cards (grade, review) values (2, 'Switchable');
insert into Cards (grade, review) values (9, 'real-time');
insert into Cards (grade, review) values (3, 'focus group');
insert into Cards (grade, review) values (2, 'bottom-line');
insert into Cards (grade, review) values (5, 'Enterprise-wide');
insert into Cards (grade, review) values (10, 'Optimized');
insert into Cards (grade, review) values (4, 'Re-engineered');
insert into Cards (grade, review) values (8, 'Networked');
insert into Cards (grade, review) values (9, 'Seamless');
insert into Cards (grade, review) values (8, 'maximized');
insert into Cards (grade, review) values (6, 'dedicated');
insert into Cards (grade, review) values (5, 'budgetary management');
insert into Cards (grade, review) values (1, 'model');
insert into Cards (grade, review) values (6, 'toolset');
insert into Cards (grade, review) values (3, 'Sharable');
insert into Cards (grade, review) values (8, 'framework');
insert into Cards (grade, review) values (4, 'Switchable');
insert into Cards (grade, review) values (6, 'flexibility');
insert into Cards (grade, review) values (3, 'solution-oriented');
insert into Cards (grade, review) values (7, 'Graphic Interface');
insert into Cards (grade, review) values (10, 'Graphical User Interface');
insert into Cards (grade, review) values (6, 'focus group');
insert into Cards (grade, review) values (3, 'Fundamental');
insert into Cards (grade, review) values (8, 'Stand-alone');
insert into Cards (grade, review) values (5, 'Multi-channelled');
insert into Cards (grade, review) values (10, 'transitional');
insert into Cards (grade, review) values (3, 'real-time');
insert into Cards (grade, review) values (3, 'responsive');
insert into Cards (grade, review) values (6, 'structure');
insert into Cards (grade, review) values (6, 'benchmark');
insert into Cards (grade, review) values (5, 'holistic');
insert into Cards (grade, review) values (1, 'regional');
insert into Cards (grade, review) values (5, 'Inverse');
insert into Cards (grade, review) values (4, 'optimizing');
insert into Cards (grade, review) values (5, 'access');
insert into Cards (grade, review) values (3, 'Proactive');
insert into Cards (grade, review) values (7, 'Graphic Interface');
insert into Cards (grade, review) values (1, 'Distributed');
insert into Cards (grade, review) values (6, 'Enterprise-wide');
insert into Cards (grade, review) values (2, 'local area network');
insert into Cards (grade, review) values (9, 'static');
insert into Cards (grade, review) values (7, 'value-added');
insert into Cards (grade, review) values (3, 'migration');
insert into Cards (grade, review) values (10, 'attitude');
insert into Cards (grade, review) values (10, 'parallelism');
insert into Cards (grade, review) values (6, 'Object-based');
insert into Cards (grade, review) values (8, 'directional');
insert into Cards (grade, review) values (9, '5th generation');
insert into Cards (grade, review) values (3, 'background');
insert into Cards (grade, review) values (10, 'logistical');
insert into Cards (grade, review) values (1, 'Decentralized');
insert into Cards (grade, review) values (1, 'Distributed');
insert into Cards (grade, review) values (8, 'Adaptive');
insert into Cards (grade, review) values (8, 'help-desk');
insert into Cards (grade, review) values (7, 'object-oriented');
insert into Cards (grade, review) values (4, 'Up-sized');
insert into Cards (grade, review) values (5, 'alliance');
insert into Cards (grade, review) values (1, 'Total');
insert into Cards (grade, review) values (1, 'moderator');
insert into Cards (grade, review) values (1, 'conglomeration');
insert into Cards (grade, review) values (3, 'system-worthy');
insert into Cards (grade, review) values (2, 'context-sensitive');
insert into Cards (grade, review) values (3, 'matrices');
insert into Cards (grade, review) values (2, 'budgetary management');
insert into Cards (grade, review) values (6, 'matrices');
insert into Cards (grade, review) values (9, 'Managed');
insert into Cards (grade, review) values (3, 'Face to face');
insert into Cards (grade, review) values (3, 'frame');
insert into Cards (grade, review) values (8, 'needs-based');
insert into Cards (grade, review) values (1, 'analyzing');
insert into Cards (grade, review) values (4, 'human-resource');
