insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pretium quis lectus suspendiss', 'Nobody', 'Jet', 'Deconstructed', 142, '2012-09-05 15:00:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui luctus rutrum nulla tellus', 'Nobody', 'Airbus', 'Deconstructed', 60, '2007-12-28 23:14:41');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('at lorem integer tincidunt ant', 'CroatiaAirlines', 'Jet', 'OnRepair', 199, '2003-12-17 13:37:46');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pharetra magna ac consequat me', 'OnSale', 'Airbus', 'Deconstructed', 196, '2012-12-31 21:47:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('molestie nibh in lectus pellen', 'EasyJet', 'CargoPlane', 'Deconstructed', 83, '2021-02-10 06:27:00');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('luctus et ultrices posuere cub', 'CroatiaAirlines', 'CargoPlane', 'Active', 79, '2007-08-14 02:35:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vestibulum sit amet cursus id ', 'AirDump', 'Airbus', 'Active', 113, '2002-06-16 05:31:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nec euismod scelerisque quam t', 'OnSale', 'Airbus', 'OnRepair', 124, '2010-01-27 05:19:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('convallis eget eleifend luctus', 'OnSale', 'Jet', 'OnRepair', 151, '2009-05-02 05:08:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rutrum nulla tellus in sagitti', 'AirDump', 'CargoPlane', 'OnRepair', 135, '2011-03-02 11:35:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu felis fusce posuere felis s', 'CroatiaAirlines', 'Jet', 'OnRepair', 120, '2002-10-20 04:12:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sapien urna pretium nisl ut vo', 'EasyJet', 'CargoPlane', 'OnRepair', 80, '2010-04-15 22:35:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('libero nam dui proin leo odio ', 'Nobody', 'CargoPlane', 'Deconstructed', 86, '2013-11-15 13:31:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('erat curabitur gravida nisi at', 'CroatiaAirlines', 'Jet', 'Active', 93, '2017-07-01 00:22:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('enim in tempor turpis nec euis', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 56, '2020-12-21 02:15:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('justo eu massa donec dapibus d', 'Nobody', 'Airbus', 'OnRepair', 128, '2019-03-02 06:24:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu interdum eu tincidunt in le', 'OnSale', 'Jet', 'OnRepair', 171, '2008-09-05 05:06:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in hac habitasse platea dictum', 'AirDump', 'Airbus', 'OnRepair', 96, '2012-10-08 09:19:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('interdum in ante vestibulum an', 'AirDump', 'Airbus', 'Active', 155, '2009-08-05 06:09:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('luctus cum sociis natoque pena', 'EasyJet', 'Airbus', 'Active', 80, '2011-09-01 03:46:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mattis egestas metus aenean fe', 'OnSale', 'Jet', 'Active', 142, '2009-09-23 14:31:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pretium iaculis justo in hac h', 'OnSale', 'CargoPlane', 'OnRepair', 176, '2020-08-15 05:59:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sit amet justo morbi ut odio c', 'Nobody', 'Jet', 'OnRepair', 112, '2007-07-22 01:51:28');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui vel nisl duis ac nibh fusc', 'CroatiaAirlines', 'Jet', 'OnRepair', 178, '2018-03-14 23:34:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('accumsan tortor quis turpis se', 'Nobody', 'Jet', 'Active', 115, '2006-06-17 14:08:00');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('turpis enim blandit mi in port', 'EasyJet', 'CargoPlane', 'Active', 99, '2016-02-15 13:21:38');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eleifend pede libero quis orci', 'Nobody', 'CargoPlane', 'Deconstructed', 153, '2016-10-19 13:50:54');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id massa id nisl venenatis lac', 'AirDump', 'Jet', 'Deconstructed', 56, '2008-06-13 08:19:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu mi nulla ac enim in tempor ', 'OnSale', 'Airbus', 'Deconstructed', 194, '1999-12-19 23:09:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dapibus dolor vel est donec od', 'OnSale', 'Jet', 'OnRepair', 168, '2005-02-25 11:50:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('libero nam dui proin leo odio ', 'CroatiaAirlines', 'Jet', 'OnRepair', 97, '2007-08-12 22:49:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla tempus vivamus in felis ', 'EasyJet', 'Airbus', 'OnRepair', 88, '2001-09-18 10:25:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sem mauris laoreet ut rhoncus ', 'Nobody', 'CargoPlane', 'OnRepair', 188, '2012-01-16 05:34:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut nunc vestibulum ante ipsum ', 'OnSale', 'CargoPlane', 'Deconstructed', 92, '2014-09-11 03:39:50');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('integer aliquet massa id lobor', 'EasyJet', 'Airbus', 'Active', 54, '2003-08-08 01:11:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ipsum dolor sit amet consectet', 'CroatiaAirlines', 'Jet', 'Deconstructed', 199, '2000-06-27 14:01:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rutrum ac lobortis vel dapibus', 'AirDump', 'CargoPlane', 'OnRepair', 76, '2010-10-19 06:49:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('at dolor quis odio consequat v', 'Nobody', 'Airbus', 'Active', 129, '2004-02-06 03:35:28');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit eu est congue elementum ', 'OnSale', 'CargoPlane', 'Active', 140, '2003-07-13 03:18:29');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pulvinar sed nisl nunc rhoncus', 'OnSale', 'Airbus', 'Active', 174, '2018-02-26 11:31:16');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('consequat lectus in est risus ', 'EasyJet', 'Jet', 'Active', 147, '2012-03-29 00:39:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ligula vehicula consequat morb', 'EasyJet', 'CargoPlane', 'Active', 200, '1999-09-22 19:23:41');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lacinia nisi venenatis tristiq', 'Nobody', 'CargoPlane', 'Deconstructed', 198, '2003-06-18 05:21:10');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ultrices posuere cubilia curae', 'CroatiaAirlines', 'CargoPlane', 'OnRepair', 130, '2006-10-06 01:58:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mattis egestas metus aenean fe', 'OnSale', 'Airbus', 'OnRepair', 104, '2016-11-10 12:02:12');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('justo lacinia eget tincidunt e', 'Nobody', 'Jet', 'OnRepair', 174, '2007-01-21 17:47:33');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pellentesque ultrices mattis o', 'Nobody', 'Jet', 'Deconstructed', 109, '2012-01-10 16:55:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('faucibus orci luctus et ultric', 'OnSale', 'Airbus', 'Deconstructed', 131, '1999-04-15 08:27:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('faucibus orci luctus et ultric', 'AirDump', 'Jet', 'OnRepair', 145, '2016-09-03 23:52:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('elementum ligula vehicula cons', 'Nobody', 'CargoPlane', 'Deconstructed', 59, '2019-06-24 13:44:07');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit id pretium iaculis diam ', 'EasyJet', 'Jet', 'Active', 159, '2004-04-04 01:55:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('est lacinia nisi venenatis tri', 'CroatiaAirlines', 'Airbus', 'Active', 163, '2005-10-08 00:32:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('venenatis non sodales sed tinc', 'Nobody', 'Airbus', 'Deconstructed', 180, '2006-01-30 08:27:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ac nibh fusce lacus purus aliq', 'OnSale', 'CargoPlane', 'Active', 192, '2005-12-05 22:57:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id nulla ultrices aliquet maec', 'OnSale', 'CargoPlane', 'Deconstructed', 66, '2017-07-02 20:34:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in eleifend quam a odio in hac', 'OnSale', 'Airbus', 'Deconstructed', 81, '2006-03-01 00:41:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sed ante vivamus tortor duis m', 'Nobody', 'Jet', 'OnRepair', 159, '2007-06-02 07:13:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('duis aliquam convallis nunc pr', 'AirDump', 'Airbus', 'OnRepair', 67, '2010-03-24 11:18:21');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in magna bibendum imperdiet nu', 'Nobody', 'Jet', 'OnRepair', 91, '2019-08-20 17:11:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('auctor sed tristique in tempus', 'CroatiaAirlines', 'Airbus', 'Active', 172, '2010-06-23 04:17:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('donec dapibus duis at velit eu', 'AirDump', 'Jet', 'OnRepair', 109, '2014-09-06 01:23:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('elementum ligula vehicula cons', 'Nobody', 'CargoPlane', 'Active', 135, '2011-04-30 02:23:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('magnis dis parturient montes n', 'CroatiaAirlines', 'Jet', 'OnRepair', 138, '2002-04-16 23:51:10');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id luctus nec molestie sed jus', 'AirDump', 'CargoPlane', 'Deconstructed', 135, '2013-02-01 23:05:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sed tristique in tempus sit am', 'AirDump', 'CargoPlane', 'Deconstructed', 167, '2004-09-23 04:44:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('donec quis orci eget orci vehi', 'AirDump', 'Airbus', 'Active', 95, '2005-08-08 06:53:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id pretium iaculis diam erat f', 'Nobody', 'CargoPlane', 'Deconstructed', 171, '2011-10-23 16:33:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla sed vel enim sit amet nu', 'CroatiaAirlines', 'CargoPlane', 'Deconstructed', 67, '1999-07-11 19:47:12');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rhoncus aliquam lacus morbi qu', 'Nobody', 'Jet', 'Active', 62, '2015-11-24 12:21:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nisi venenatis tristique fusce', 'AirDump', 'Airbus', 'Active', 106, '2005-08-31 01:09:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('etiam faucibus cursus urna ut ', 'CroatiaAirlines', 'Jet', 'Active', 105, '2002-11-02 11:41:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('purus aliquet at feugiat non p', 'OnSale', 'Airbus', 'Active', 95, '2005-09-27 21:12:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in magna bibendum imperdiet nu', 'AirDump', 'Jet', 'Active', 70, '2020-04-29 11:50:41');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('cubilia curae nulla dapibus do', 'EasyJet', 'Airbus', 'OnRepair', 115, '2007-06-16 21:36:54');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut massa volutpat convallis mo', 'EasyJet', 'Airbus', 'Deconstructed', 174, '2011-01-22 23:58:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet lobortis sapien sapien no', 'EasyJet', 'CargoPlane', 'Deconstructed', 101, '2009-01-05 14:36:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('purus aliquet at feugiat non p', 'OnSale', 'Airbus', 'Deconstructed', 81, '2008-06-27 23:26:11');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('blandit ultrices enim lorem ip', 'EasyJet', 'Airbus', 'Active', 190, '2019-01-03 17:06:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sapien a libero nam dui proin ', 'Nobody', 'Jet', 'OnRepair', 190, '2008-08-14 04:39:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut rhoncus aliquet pulvinar se', 'OnSale', 'Airbus', 'Deconstructed', 107, '2009-12-28 12:37:08');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ullamcorper augue a suscipit n', 'OnSale', 'Jet', 'Active', 135, '2017-07-11 21:11:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('auctor gravida sem praesent id', 'OnSale', 'Airbus', 'Deconstructed', 136, '2004-08-14 19:41:33');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('maecenas tristique est et temp', 'OnSale', 'Airbus', 'Deconstructed', 178, '2004-01-06 12:42:11');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('platea dictumst etiam faucibus', 'Nobody', 'CargoPlane', 'Active', 121, '2000-11-13 05:58:22');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('convallis tortor risus dapibus', 'Nobody', 'CargoPlane', 'Active', 173, '2017-07-11 02:14:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ullamcorper purus sit amet nul', 'Nobody', 'CargoPlane', 'OnRepair', 166, '2014-02-04 07:45:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rhoncus dui vel sem sed sagitt', 'Nobody', 'Airbus', 'Deconstructed', 154, '2006-07-07 17:37:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quisque id justo sit amet sapi', 'OnSale', 'Jet', 'OnRepair', 99, '2012-06-20 17:55:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel nisl duis ac nibh fusce la', 'Nobody', 'Jet', 'OnRepair', 171, '2004-07-14 19:29:29');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quam nec dui luctus rutrum nul', 'Nobody', 'Airbus', 'Active', 85, '2014-02-23 02:08:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('libero nullam sit amet turpis ', 'CroatiaAirlines', 'CargoPlane', 'Active', 129, '2011-12-17 04:12:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ligula vehicula consequat morb', 'Nobody', 'Airbus', 'Active', 151, '2016-05-10 06:45:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pede ullamcorper augue a susci', 'CroatiaAirlines', 'Jet', 'Active', 141, '2007-09-26 19:12:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vivamus metus arcu adipiscing ', 'OnSale', 'Airbus', 'Deconstructed', 122, '2002-11-13 10:44:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('egestas metus aenean fermentum', 'CroatiaAirlines', 'CargoPlane', 'Active', 165, '2017-09-20 11:44:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lorem vitae mattis nibh ligula', 'CroatiaAirlines', 'Jet', 'Active', 145, '2010-08-04 13:10:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id justo sit amet sapien digni', 'EasyJet', 'CargoPlane', 'Active', 127, '2017-03-01 19:27:02');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel pede morbi porttitor lorem', 'AirDump', 'Airbus', 'Active', 91, '2006-09-26 08:48:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla sed accumsan felis ut at', 'AirDump', 'CargoPlane', 'OnRepair', 61, '2015-11-15 04:32:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('potenti in eleifend quam a odi', 'OnSale', 'Airbus', 'Deconstructed', 90, '2001-01-21 19:59:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('donec odio justo sollicitudin ', 'OnSale', 'Jet', 'Deconstructed', 174, '2007-12-01 01:18:10');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nibh ligula nec sem duis aliqu', 'Nobody', 'Jet', 'Active', 68, '2000-01-09 11:48:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('et ultrices posuere cubilia cu', 'OnSale', 'CargoPlane', 'OnRepair', 98, '2017-06-29 22:53:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pede venenatis non sodales sed', 'CroatiaAirlines', 'Airbus', 'Active', 90, '2012-12-11 02:11:08');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('porttitor lacus at turpis done', 'Nobody', 'CargoPlane', 'Deconstructed', 86, '2007-08-27 21:52:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('faucibus accumsan odio curabit', 'OnSale', 'Jet', 'OnRepair', 183, '2015-08-12 09:31:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lobortis convallis tortor risu', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 100, '2009-12-20 17:44:07');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non velit nec nisi vulputate n', 'Nobody', 'Jet', 'Active', 108, '2018-11-28 17:36:02');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('arcu adipiscing molestie hendr', 'CroatiaAirlines', 'CargoPlane', 'OnRepair', 195, '2011-07-20 12:13:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('purus eu magna vulputate luctu', 'Nobody', 'Airbus', 'Deconstructed', 164, '2003-02-08 09:43:07');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mauris viverra diam vitae quam', 'CroatiaAirlines', 'Airbus', 'OnRepair', 54, '2007-07-26 15:19:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('at ipsum ac tellus semper inte', 'AirDump', 'Airbus', 'Deconstructed', 66, '2007-05-29 21:54:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquam quis turpis eget elit ', 'Nobody', 'Airbus', 'OnRepair', 153, '2012-07-04 20:43:12');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('integer ac neque duis bibendum', 'OnSale', 'CargoPlane', 'Active', 117, '2008-10-24 02:21:07');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('risus semper porta volutpat qu', 'Nobody', 'Jet', 'Deconstructed', 145, '2018-09-20 22:00:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('consequat nulla nisl nunc nisl', 'OnSale', 'CargoPlane', 'Deconstructed', 140, '2004-08-21 07:57:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel sem sed sagittis nam congu', 'AirDump', 'Airbus', 'Deconstructed', 145, '2013-04-08 03:50:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nunc proin at turpis a pede po', 'AirDump', 'CargoPlane', 'Deconstructed', 160, '2005-11-29 03:50:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('fringilla rhoncus mauris enim ', 'Nobody', 'CargoPlane', 'OnRepair', 65, '2016-04-21 05:24:27');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('morbi a ipsum integer a nibh i', 'Nobody', 'CargoPlane', 'Deconstructed', 85, '1999-05-20 03:26:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut dolor morbi vel lectus in q', 'EasyJet', 'CargoPlane', 'OnRepair', 192, '1999-09-24 05:57:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('turpis adipiscing lorem vitae ', 'EasyJet', 'Jet', 'OnRepair', 67, '2020-03-07 12:14:41');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quis augue luctus tincidunt nu', 'OnSale', 'CargoPlane', 'OnRepair', 62, '2001-11-28 04:49:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('integer ac neque duis bibendum', 'CroatiaAirlines', 'Airbus', 'Active', 117, '2015-08-28 20:05:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('cursus urna ut tellus nulla ut', 'OnSale', 'Airbus', 'Deconstructed', 143, '2016-09-03 01:54:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut mauris eget massa tempor co', 'OnSale', 'Airbus', 'Deconstructed', 185, '2015-03-03 23:18:29');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('duis at velit eu est congue el', 'EasyJet', 'Airbus', 'OnRepair', 140, '2018-10-29 10:25:35');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('habitasse platea dictumst maec', 'OnSale', 'CargoPlane', 'Deconstructed', 95, '2002-11-26 06:57:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sit amet erat nulla tempus viv', 'CroatiaAirlines', 'CargoPlane', 'Deconstructed', 142, '2016-09-07 12:48:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('hac habitasse platea dictumst ', 'EasyJet', 'CargoPlane', 'Active', 78, '2000-01-12 03:41:16');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet eros suspendisse accumsan', 'OnSale', 'Jet', 'Active', 101, '2020-02-14 22:10:27');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dolor morbi vel lectus in quam', 'AirDump', 'Airbus', 'Deconstructed', 166, '2001-03-12 20:59:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('habitasse platea dictumst etia', 'OnSale', 'Airbus', 'OnRepair', 64, '2012-08-04 01:46:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla quisque arcu libero rutr', 'OnSale', 'Airbus', 'OnRepair', 180, '2000-09-29 11:41:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu est congue elementum in hac', 'OnSale', 'CargoPlane', 'Deconstructed', 178, '2015-04-09 09:25:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rhoncus dui vel sem sed sagitt', 'OnSale', 'Airbus', 'OnRepair', 170, '2010-05-18 11:15:28');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla sed accumsan felis ut at', 'EasyJet', 'Airbus', 'OnRepair', 133, '2019-09-12 00:49:08');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('volutpat quam pede lobortis li', 'Nobody', 'Airbus', 'Active', 94, '2002-11-28 14:35:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('diam neque vestibulum eget vul', 'Nobody', 'Airbus', 'Deconstructed', 59, '2017-03-13 17:38:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('orci vehicula condimentum cura', 'Nobody', 'Jet', 'Active', 72, '2002-06-03 12:10:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('venenatis non sodales sed tinc', 'AirDump', 'CargoPlane', 'Deconstructed', 61, '2020-01-26 12:56:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('justo aliquam quis turpis eget', 'Nobody', 'Airbus', 'OnRepair', 83, '2003-06-04 17:33:50');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut massa quis augue luctus tin', 'OnSale', 'CargoPlane', 'Deconstructed', 122, '2004-08-06 21:07:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui vel sem sed sagittis nam c', 'OnSale', 'Jet', 'Active', 77, '2016-01-09 15:21:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non mi integer ac neque duis b', 'Nobody', 'CargoPlane', 'Deconstructed', 198, '2011-07-19 07:24:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('morbi sem mauris laoreet ut rh', 'CroatiaAirlines', 'Jet', 'Active', 147, '2013-05-24 12:37:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('accumsan tellus nisi eu orci m', 'OnSale', 'Jet', 'OnRepair', 59, '1999-06-24 21:53:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet justo morbi ut odio cras ', 'Nobody', 'Airbus', 'OnRepair', 74, '2007-08-12 03:41:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('curae mauris viverra diam vita', 'AirDump', 'Jet', 'Deconstructed', 54, '2003-06-21 05:27:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ultrices enim lorem ipsum dolo', 'Nobody', 'Airbus', 'Deconstructed', 88, '2010-01-29 06:28:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('tincidunt eget tempus vel pede', 'Nobody', 'CargoPlane', 'OnRepair', 103, '2018-08-20 07:54:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('suscipit nulla elit ac nulla s', 'OnSale', 'Jet', 'OnRepair', 67, '2001-02-18 16:00:00');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id ligula suspendisse ornare c', 'Nobody', 'CargoPlane', 'Deconstructed', 120, '2017-04-14 05:49:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quisque ut erat curabitur grav', 'EasyJet', 'Jet', 'OnRepair', 63, '2007-01-12 10:28:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('consequat nulla nisl nunc nisl', 'Nobody', 'Airbus', 'OnRepair', 178, '2002-09-22 15:25:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pede justo eu massa donec dapi', 'Nobody', 'CargoPlane', 'Active', 106, '2004-05-25 02:28:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mi integer ac neque duis biben', 'EasyJet', 'Airbus', 'OnRepair', 98, '2007-09-03 19:25:27');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu sapien cursus vestibulum pr', 'Nobody', 'Airbus', 'Active', 105, '2011-07-30 19:00:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('luctus rutrum nulla tellus in ', 'AirDump', 'CargoPlane', 'Deconstructed', 101, '2003-04-21 07:41:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nec nisi vulputate nonummy mae', 'AirDump', 'Jet', 'OnRepair', 171, '2019-02-16 01:04:43');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vitae consectetuer eget rutrum', 'OnSale', 'Airbus', 'Active', 56, '2002-09-22 12:20:28');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('condimentum id luctus nec mole', 'OnSale', 'Jet', 'Active', 69, '2003-04-01 22:48:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('blandit non interdum in ante v', 'Nobody', 'Airbus', 'Deconstructed', 154, '2016-08-25 15:52:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui luctus rutrum nulla tellus', 'Nobody', 'CargoPlane', 'Deconstructed', 199, '2007-02-21 07:48:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nisi venenatis tristique fusce', 'AirDump', 'CargoPlane', 'OnRepair', 127, '2003-01-04 03:18:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('a libero nam dui proin leo odi', 'AirDump', 'Jet', 'Active', 127, '2019-05-18 01:40:56');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('praesent id massa id nisl vene', 'Nobody', 'Jet', 'Deconstructed', 100, '2017-05-31 20:45:38');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('at velit vivamus vel nulla ege', 'AirDump', 'Jet', 'OnRepair', 176, '2015-05-13 13:10:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('condimentum curabitur in liber', 'OnSale', 'CargoPlane', 'Active', 163, '2016-01-02 01:52:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget congue eget semper rutrum', 'Nobody', 'Jet', 'Deconstructed', 194, '2019-11-25 14:23:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mauris morbi non lectus aliqua', 'Nobody', 'CargoPlane', 'Deconstructed', 122, '2018-08-12 03:38:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('molestie sed justo pellentesqu', 'Nobody', 'Jet', 'Active', 90, '2020-09-07 18:33:59');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('erat quisque erat eros viverra', 'EasyJet', 'Jet', 'Deconstructed', 71, '2005-12-16 16:32:16');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('hac habitasse platea dictumst ', 'AirDump', 'Airbus', 'Active', 96, '2017-09-22 16:41:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('adipiscing lorem vitae mattis ', 'OnSale', 'Airbus', 'OnRepair', 174, '2000-05-09 12:38:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quam pede lobortis ligula sit ', 'CroatiaAirlines', 'Airbus', 'Active', 130, '2009-12-02 21:49:29');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('elementum in hac habitasse pla', 'AirDump', 'CargoPlane', 'Deconstructed', 159, '2002-12-01 21:48:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('magna vulputate luctus cum soc', 'AirDump', 'CargoPlane', 'OnRepair', 76, '2020-05-02 03:00:59');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('tincidunt lacus at velit vivam', 'OnSale', 'Jet', 'Deconstructed', 63, '2001-11-08 17:15:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('integer pede justo lacinia ege', 'EasyJet', 'Jet', 'Active', 151, '2000-12-06 10:13:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in tempus sit amet sem fusce c', 'OnSale', 'CargoPlane', 'Active', 61, '2006-04-10 11:34:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('augue luctus tincidunt nulla m', 'OnSale', 'Airbus', 'Active', 106, '2001-10-26 17:32:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rhoncus aliquam lacus morbi qu', 'EasyJet', 'Airbus', 'Active', 170, '2003-06-07 01:51:59');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nullam molestie nibh in lectus', 'OnSale', 'CargoPlane', 'OnRepair', 119, '2017-03-24 18:02:54');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('suscipit a feugiat et eros ves', 'EasyJet', 'CargoPlane', 'OnRepair', 81, '2018-07-25 22:45:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ultrices enim lorem ipsum dolo', 'Nobody', 'CargoPlane', 'OnRepair', 124, '2014-09-20 20:01:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non ligula pellentesque ultric', 'EasyJet', 'CargoPlane', 'Deconstructed', 134, '2017-06-05 18:32:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut at dolor quis odio consequa', 'OnSale', 'Airbus', 'Deconstructed', 129, '2008-03-14 08:38:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quis orci nullam molestie nibh', 'Nobody', 'Airbus', 'Deconstructed', 63, '2012-09-03 20:05:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vivamus vel nulla eget eros el', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 120, '2006-08-19 05:45:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla eget eros elementum pell', 'CroatiaAirlines', 'Jet', 'Deconstructed', 158, '2008-01-05 02:13:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquam convallis nunc proin a', 'CroatiaAirlines', 'CargoPlane', 'Active', 163, '1999-11-20 12:17:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vehicula consequat morbi a ips', 'Nobody', 'CargoPlane', 'Deconstructed', 141, '2020-03-07 21:58:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ridiculus mus etiam vel augue ', 'EasyJet', 'Jet', 'OnRepair', 182, '2012-01-22 03:16:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nibh quisque id justo sit amet', 'Nobody', 'Airbus', 'Active', 66, '2009-06-18 10:10:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel lectus in quam fringilla r', 'AirDump', 'CargoPlane', 'Active', 139, '2019-11-01 20:56:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquam lacus morbi quis torto', 'OnSale', 'Airbus', 'Active', 184, '2009-03-30 07:19:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('porta volutpat erat quisque er', 'Nobody', 'Jet', 'Deconstructed', 73, '2003-04-11 11:26:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('phasellus id sapien in sapien ', 'CroatiaAirlines', 'Airbus', 'OnRepair', 184, '2021-02-10 19:35:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('orci mauris lacinia sapien qui', 'AirDump', 'Jet', 'OnRepair', 94, '2018-01-09 02:04:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vitae nisl aenean lectus pelle', 'OnSale', 'CargoPlane', 'OnRepair', 196, '2007-04-26 21:35:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu nibh quisque id justo sit a', 'AirDump', 'Jet', 'OnRepair', 85, '2015-04-27 18:31:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('praesent blandit lacinia erat ', 'Nobody', 'Jet', 'OnRepair', 169, '2000-12-11 06:07:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('a feugiat et eros vestibulum a', 'OnSale', 'CargoPlane', 'Active', 86, '2006-01-18 06:32:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dolor morbi vel lectus in quam', 'CroatiaAirlines', 'Jet', 'Deconstructed', 184, '2013-11-26 17:16:46');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sem praesent id massa id nisl ', 'Nobody', 'Jet', 'Active', 50, '2020-12-11 13:56:35');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('odio cras mi pede malesuada in', 'Nobody', 'Jet', 'Active', 100, '2009-09-08 10:27:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('praesent blandit lacinia erat ', 'Nobody', 'Jet', 'OnRepair', 99, '2016-05-04 09:36:02');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sapien cum sociis natoque pena', 'CroatiaAirlines', 'Jet', 'Deconstructed', 174, '2006-09-28 16:10:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in quam fringilla rhoncus maur', 'Nobody', 'Jet', 'Active', 148, '2003-11-12 17:13:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in est risus auctor sed tristi', 'CroatiaAirlines', 'Jet', 'Deconstructed', 88, '2012-06-04 05:46:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('malesuada in imperdiet et comm', 'Nobody', 'Airbus', 'OnRepair', 66, '2019-03-23 11:48:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('justo lacinia eget tincidunt e', 'OnSale', 'Jet', 'Deconstructed', 96, '2009-07-09 15:53:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sed lacus morbi sem mauris lao', 'CroatiaAirlines', 'Jet', 'OnRepair', 75, '2017-11-13 05:10:33');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non pretium quis lectus suspen', 'CroatiaAirlines', 'CargoPlane', 'Deconstructed', 76, '2015-09-22 08:46:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nullam orci pede venenatis non', 'OnSale', 'CargoPlane', 'Active', 155, '1999-08-31 15:07:54');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('neque aenean auctor gravida se', 'OnSale', 'Jet', 'OnRepair', 57, '2015-10-23 07:06:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('viverra diam vitae quam suspen', 'AirDump', 'Jet', 'OnRepair', 83, '2003-02-01 12:55:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nunc donec quis orci eget orci', 'OnSale', 'Jet', 'Deconstructed', 131, '2003-04-25 23:58:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet cursus id turpis integer ', 'OnSale', 'Airbus', 'Deconstructed', 166, '2008-12-27 15:39:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in sapien iaculis congue vivam', 'CroatiaAirlines', 'Jet', 'Deconstructed', 138, '1999-05-11 08:22:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit vivamus vel nulla eget e', 'Nobody', 'CargoPlane', 'Deconstructed', 114, '2012-12-25 17:06:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquam quis turpis eget elit ', 'OnSale', 'CargoPlane', 'OnRepair', 78, '2012-02-29 17:41:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('libero convallis eget eleifend', 'OnSale', 'CargoPlane', 'Active', 55, '2003-02-26 04:36:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut odio cras mi pede malesuada', 'OnSale', 'CargoPlane', 'Deconstructed', 125, '2011-02-19 05:50:27');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sit amet eros suspendisse accu', 'OnSale', 'CargoPlane', 'OnRepair', 171, '2015-01-25 19:04:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('cursus id turpis integer aliqu', 'Nobody', 'Airbus', 'Active', 114, '2019-03-18 07:14:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui proin leo odio porttitor i', 'CroatiaAirlines', 'Jet', 'OnRepair', 104, '2008-07-18 16:40:38');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('cras non velit nec nisi vulput', 'Nobody', 'Jet', 'Deconstructed', 167, '2009-06-03 22:41:46');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('montes nascetur ridiculus mus ', 'Nobody', 'CargoPlane', 'OnRepair', 87, '2010-05-06 18:23:33');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('varius integer ac leo pellente', 'OnSale', 'Airbus', 'Active', 56, '2014-07-11 20:41:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('semper sapien a libero nam dui', 'AirDump', 'CargoPlane', 'Active', 68, '2000-01-25 08:33:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('enim blandit mi in porttitor p', 'EasyJet', 'Airbus', 'Active', 85, '2020-06-07 09:31:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ac tellus semper interdum maur', 'CroatiaAirlines', 'CargoPlane', 'OnRepair', 76, '1999-06-06 05:56:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('turpis donec posuere metus vit', 'OnSale', 'Airbus', 'OnRepair', 183, '2005-07-07 18:10:22');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('neque duis bibendum morbi non ', 'EasyJet', 'CargoPlane', 'OnRepair', 82, '2014-03-12 11:13:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sit amet justo morbi ut odio c', 'EasyJet', 'Airbus', 'OnRepair', 82, '2020-02-11 03:40:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('cubilia curae donec pharetra m', 'OnSale', 'CargoPlane', 'OnRepair', 75, '2008-05-15 02:34:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('luctus et ultrices posuere cub', 'OnSale', 'Airbus', 'Deconstructed', 89, '2016-01-01 18:57:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nec nisi volutpat eleifend don', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 138, '2017-10-10 09:49:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('proin risus praesent lectus ve', 'Nobody', 'Jet', 'Active', 150, '2018-01-29 04:34:50');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('iaculis congue vivamus metus a', 'OnSale', 'Airbus', 'Deconstructed', 121, '2018-04-26 14:57:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('phasellus in felis donec sempe', 'OnSale', 'Jet', 'OnRepair', 166, '2003-08-02 23:42:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('curabitur convallis duis conse', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 146, '2004-01-14 10:00:50');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sagittis sapien cum sociis nat', 'OnSale', 'CargoPlane', 'Active', 90, '2002-09-01 21:49:41');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sit amet eros suspendisse accu', 'OnSale', 'Airbus', 'Active', 110, '2006-03-16 21:42:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('est risus auctor sed tristique', 'CroatiaAirlines', 'Jet', 'OnRepair', 130, '2008-12-28 17:55:02');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('fermentum justo nec condimentu', 'AirDump', 'Airbus', 'Deconstructed', 84, '2013-12-04 02:48:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('semper rutrum nulla nunc purus', 'EasyJet', 'Jet', 'OnRepair', 97, '2016-01-22 23:54:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sapien urna pretium nisl ut vo', 'Nobody', 'Jet', 'Active', 157, '2004-04-27 12:58:29');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ridiculus mus etiam vel augue ', 'CroatiaAirlines', 'Airbus', 'Active', 128, '2004-05-19 03:20:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ligula nec sem duis aliquam co', 'Nobody', 'Jet', 'OnRepair', 57, '2002-12-06 20:26:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id mauris vulputate elementum ', 'OnSale', 'CargoPlane', 'Deconstructed', 162, '2009-05-11 03:27:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut volutpat sapien arcu sed au', 'AirDump', 'Jet', 'Active', 165, '2005-10-20 17:43:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eros vestibulum ac est lacinia', 'Nobody', 'Airbus', 'OnRepair', 200, '2004-04-11 19:53:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nisl venenatis lacinia aenean ', 'Nobody', 'CargoPlane', 'Active', 61, '2003-12-26 12:00:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('felis sed interdum venenatis t', 'OnSale', 'Jet', 'Deconstructed', 171, '2000-12-01 06:57:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet consectetuer adipiscing e', 'AirDump', 'Jet', 'Active', 125, '2006-12-11 00:09:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('adipiscing molestie hendrerit ', 'EasyJet', 'CargoPlane', 'OnRepair', 112, '2017-08-26 06:33:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non mi integer ac neque duis b', 'Nobody', 'Airbus', 'Deconstructed', 162, '1999-08-10 23:09:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('porta volutpat erat quisque er', 'Nobody', 'Jet', 'Deconstructed', 104, '2008-03-11 02:29:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('natoque penatibus et magnis di', 'Nobody', 'Jet', 'OnRepair', 64, '2010-05-10 12:02:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel pede morbi porttitor lorem', 'EasyJet', 'Airbus', 'Active', 85, '1999-11-13 20:16:46');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non pretium quis lectus suspen', 'EasyJet', 'CargoPlane', 'OnRepair', 135, '2004-07-23 22:16:02');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget tempus vel pede morbi por', 'Nobody', 'Airbus', 'Deconstructed', 157, '2005-05-27 06:42:48');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('duis consequat dui nec nisi vo', 'Nobody', 'CargoPlane', 'Deconstructed', 156, '2015-09-16 13:30:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('leo odio porttitor id consequa', 'EasyJet', 'Jet', 'Deconstructed', 145, '2010-07-03 05:34:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('augue a suscipit nulla elit ac', 'OnSale', 'Airbus', 'OnRepair', 178, '2020-09-29 22:24:29');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lobortis sapien sapien non mi ', 'Nobody', 'Airbus', 'Active', 185, '1999-08-25 04:26:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut tellus nulla ut erat id mau', 'EasyJet', 'Airbus', 'Deconstructed', 95, '2018-10-08 07:13:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla nisl nunc nisl duis bibe', 'Nobody', 'Jet', 'Deconstructed', 126, '2003-09-06 13:23:12');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui proin leo odio porttitor i', 'AirDump', 'Jet', 'OnRepair', 176, '2011-06-06 11:07:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lacus morbi quis tortor id nul', 'OnSale', 'Airbus', 'OnRepair', 105, '2016-10-12 00:39:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in eleifend quam a odio in hac', 'OnSale', 'Jet', 'Deconstructed', 109, '2016-11-15 14:50:08');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('elementum eu interdum eu tinci', 'Nobody', 'CargoPlane', 'OnRepair', 94, '2009-05-10 09:09:53');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquam convallis nunc proin a', 'Nobody', 'Airbus', 'Deconstructed', 87, '2006-04-07 01:37:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut massa quis augue luctus tin', 'Nobody', 'CargoPlane', 'OnRepair', 72, '2018-01-28 10:36:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id nulla ultrices aliquet maec', 'Nobody', 'CargoPlane', 'Deconstructed', 126, '2005-06-13 15:28:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut mauris eget massa tempor co', 'Nobody', 'Jet', 'OnRepair', 154, '2005-07-25 12:09:10');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('libero nam dui proin leo odio ', 'OnSale', 'CargoPlane', 'Active', 109, '2010-01-10 04:56:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sed vestibulum sit amet cursus', 'EasyJet', 'CargoPlane', 'OnRepair', 182, '2006-01-24 11:44:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ipsum integer a nibh in quis j', 'OnSale', 'CargoPlane', 'OnRepair', 62, '2016-06-14 02:00:46');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('at nibh in hac habitasse plate', 'Nobody', 'Jet', 'OnRepair', 193, '2005-11-13 22:45:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla elit ac nulla sed vel en', 'OnSale', 'CargoPlane', 'Deconstructed', 165, '2003-04-04 09:38:07');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dapibus dolor vel est donec od', 'CroatiaAirlines', 'Airbus', 'Active', 70, '2019-09-05 06:48:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('diam vitae quam suspendisse po', 'EasyJet', 'Jet', 'Deconstructed', 89, '2002-03-11 02:57:10');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('erat fermentum justo nec condi', 'OnSale', 'Jet', 'Active', 140, '2004-08-29 20:31:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('curae donec pharetra magna ves', 'AirDump', 'Airbus', 'Active', 171, '2020-11-28 08:13:08');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ipsum praesent blandit lacinia', 'Nobody', 'Airbus', 'Deconstructed', 69, '2000-10-09 11:03:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mattis odio donec vitae nisi n', 'Nobody', 'Airbus', 'OnRepair', 177, '2002-12-06 15:37:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('magna ac consequat metus sapie', 'Nobody', 'CargoPlane', 'Active', 191, '2014-07-08 14:34:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ipsum primis in faucibus orci ', 'EasyJet', 'CargoPlane', 'Deconstructed', 157, '2006-06-20 20:05:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('erat eros viverra eget congue ', 'Nobody', 'Airbus', 'Deconstructed', 182, '2009-12-06 22:40:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('suspendisse potenti in eleifen', 'AirDump', 'Jet', 'Deconstructed', 106, '2019-04-11 00:35:50');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('tempor convallis nulla neque l', 'OnSale', 'CargoPlane', 'Deconstructed', 106, '2000-07-14 05:41:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla suscipit ligula in lacus', 'Nobody', 'CargoPlane', 'OnRepair', 123, '2015-11-01 11:31:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('odio curabitur convallis duis ', 'CroatiaAirlines', 'Airbus', 'OnRepair', 177, '2004-02-01 06:30:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lectus pellentesque at nulla s', 'Nobody', 'CargoPlane', 'Deconstructed', 89, '2005-07-29 13:13:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu mi nulla ac enim in tempor ', 'Nobody', 'Jet', 'OnRepair', 156, '2008-09-11 11:51:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dis parturient montes nascetur', 'AirDump', 'CargoPlane', 'Active', 175, '2006-04-10 22:19:08');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quis orci nullam molestie nibh', 'OnSale', 'Airbus', 'Active', 118, '2008-07-12 17:29:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nascetur ridiculus mus vivamus', 'EasyJet', 'Jet', 'Active', 123, '2007-03-06 19:01:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('donec diam neque vestibulum eg', 'Nobody', 'CargoPlane', 'Deconstructed', 141, '2020-02-22 09:16:50');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lectus pellentesque eget nunc ', 'OnSale', 'Airbus', 'Deconstructed', 77, '2016-03-28 11:31:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ultrices erat tortor sollicitu', 'OnSale', 'Airbus', 'OnRepair', 92, '2012-06-01 23:33:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('faucibus cursus urna ut tellus', 'AirDump', 'CargoPlane', 'Deconstructed', 159, '2014-03-15 08:56:00');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet erat nulla tempus vivamus', 'CroatiaAirlines', 'CargoPlane', 'Active', 143, '2016-08-28 08:14:10');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('praesent blandit nam nulla int', 'AirDump', 'CargoPlane', 'Active', 186, '2019-09-29 06:50:10');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('morbi sem mauris laoreet ut rh', 'AirDump', 'Airbus', 'OnRepair', 110, '2009-06-22 15:03:56');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mauris non ligula pellentesque', 'OnSale', 'Jet', 'OnRepair', 183, '2008-03-18 15:27:35');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('luctus ultricies eu nibh quisq', 'Nobody', 'CargoPlane', 'Active', 90, '2013-02-17 00:39:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quis libero nullam sit amet tu', 'Nobody', 'CargoPlane', 'Deconstructed', 185, '2002-02-28 12:09:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('metus arcu adipiscing molestie', 'Nobody', 'CargoPlane', 'OnRepair', 118, '2015-03-31 20:24:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ligula suspendisse ornare cons', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 107, '2015-06-19 14:30:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quis turpis sed ante vivamus t', 'OnSale', 'Airbus', 'Active', 53, '2007-01-11 23:23:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('orci luctus et ultrices posuer', 'Nobody', 'Jet', 'OnRepair', 140, '2014-03-02 02:11:08');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('justo lacinia eget tincidunt e', 'CroatiaAirlines', 'CargoPlane', 'OnRepair', 64, '2017-10-17 16:10:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nam nulla integer pede justo l', 'OnSale', 'Airbus', 'OnRepair', 177, '2001-05-26 06:06:11');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('felis eu sapien cursus vestibu', 'OnSale', 'Jet', 'Deconstructed', 163, '2011-08-28 15:18:11');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ante vestibulum ante ipsum pri', 'EasyJet', 'Airbus', 'OnRepair', 103, '2020-09-11 18:37:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget eleifend luctus ultricies', 'Nobody', 'Jet', 'Deconstructed', 196, '2004-10-17 23:59:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('faucibus accumsan odio curabit', 'CroatiaAirlines', 'CargoPlane', 'OnRepair', 73, '2012-09-18 12:59:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('fringilla rhoncus mauris enim ', 'AirDump', 'Jet', 'Deconstructed', 190, '2000-01-30 01:39:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mauris laoreet ut rhoncus aliq', 'OnSale', 'Airbus', 'Active', 137, '2009-07-07 22:25:15');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aenean fermentum donec ut maur', 'AirDump', 'Jet', 'Deconstructed', 90, '2007-08-26 11:56:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('consequat ut nulla sed accumsa', 'OnSale', 'Jet', 'OnRepair', 194, '2014-01-23 00:04:56');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non velit donec diam neque ves', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 133, '2018-07-06 13:03:16');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('non velit donec diam neque ves', 'OnSale', 'Airbus', 'OnRepair', 185, '2003-10-21 06:11:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet turpis elementum ligula v', 'OnSale', 'CargoPlane', 'Active', 54, '2004-09-05 22:50:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('tincidunt nulla mollis molesti', 'OnSale', 'Jet', 'Active', 146, '2014-04-04 10:48:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lorem ipsum dolor sit amet con', 'OnSale', 'Airbus', 'OnRepair', 123, '2004-09-04 04:21:43');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('etiam vel augue vestibulum rut', 'Nobody', 'Jet', 'Active', 136, '2014-05-24 01:40:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquet maecenas leo odio cond', 'EasyJet', 'CargoPlane', 'OnRepair', 84, '2016-05-24 03:20:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vulputate justo in blandit ult', 'OnSale', 'Airbus', 'Deconstructed', 181, '2014-05-01 01:08:27');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ultrices vel augue vestibulum ', 'Nobody', 'Airbus', 'OnRepair', 196, '2016-06-27 07:11:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('odio consequat varius integer ', 'OnSale', 'CargoPlane', 'OnRepair', 113, '2003-03-31 21:26:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('curae mauris viverra diam vita', 'OnSale', 'Airbus', 'Deconstructed', 192, '2002-05-30 10:27:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('curae duis faucibus accumsan o', 'CroatiaAirlines', 'CargoPlane', 'Active', 200, '2020-02-12 18:30:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dolor quis odio consequat vari', 'EasyJet', 'CargoPlane', 'Deconstructed', 52, '2010-01-01 11:01:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('orci luctus et ultrices posuer', 'Nobody', 'Airbus', 'Deconstructed', 113, '2003-03-01 10:41:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut blandit non interdum in ant', 'Nobody', 'Airbus', 'Deconstructed', 122, '2007-06-04 13:22:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('at velit vivamus vel nulla ege', 'EasyJet', 'Jet', 'Deconstructed', 150, '1999-10-17 23:18:04');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('viverra pede ac diam cras pell', 'Nobody', 'Jet', 'OnRepair', 87, '2004-09-23 17:23:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nunc donec quis orci eget orci', 'Nobody', 'CargoPlane', 'Deconstructed', 168, '2005-09-24 23:04:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquet maecenas leo odio cond', 'Nobody', 'CargoPlane', 'Active', 97, '1999-12-07 09:50:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nisi nam ultrices libero non m', 'CroatiaAirlines', 'CargoPlane', 'Deconstructed', 149, '2019-11-09 16:45:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nec nisi volutpat eleifend don', 'OnSale', 'CargoPlane', 'Active', 186, '2007-08-06 11:43:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vestibulum ante ipsum primis i', 'EasyJet', 'CargoPlane', 'OnRepair', 174, '2009-12-19 22:32:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet nunc viverra dapibus null', 'EasyJet', 'Jet', 'Active', 103, '2006-09-02 14:15:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rutrum at lorem integer tincid', 'EasyJet', 'Airbus', 'Deconstructed', 54, '2010-10-10 07:51:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('molestie nibh in lectus pellen', 'CroatiaAirlines', 'Airbus', 'OnRepair', 178, '2016-09-29 14:13:59');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel augue vestibulum ante ipsu', 'CroatiaAirlines', 'Jet', 'OnRepair', 85, '2009-04-14 04:33:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ullamcorper purus sit amet nul', 'Nobody', 'Airbus', 'OnRepair', 52, '2014-02-16 11:27:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('odio justo sollicitudin ut sus', 'Nobody', 'Airbus', 'Active', 177, '2021-02-08 05:21:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nisi nam ultrices libero non m', 'OnSale', 'Jet', 'OnRepair', 137, '2007-06-26 23:53:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in consequat ut nulla sed accu', 'CroatiaAirlines', 'Jet', 'Active', 182, '2004-03-16 02:43:30');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet eros suspendisse accumsan', 'Nobody', 'Jet', 'OnRepair', 145, '2012-10-09 01:22:11');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('et ultrices posuere cubilia cu', 'CroatiaAirlines', 'Airbus', 'Active', 145, '2019-08-16 07:13:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('primis in faucibus orci luctus', 'AirDump', 'Airbus', 'OnRepair', 161, '2001-11-29 19:31:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui luctus rutrum nulla tellus', 'OnSale', 'Airbus', 'Active', 133, '2008-06-10 03:22:12');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('praesent id massa id nisl vene', 'AirDump', 'Airbus', 'Deconstructed', 55, '2012-03-25 08:14:27');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla tempus vivamus in felis ', 'Nobody', 'CargoPlane', 'Deconstructed', 111, '2006-07-31 20:50:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('suspendisse potenti nullam por', 'EasyJet', 'Airbus', 'OnRepair', 65, '2017-01-10 19:54:28');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('interdum in ante vestibulum an', 'OnSale', 'CargoPlane', 'Active', 76, '2001-06-25 08:26:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('luctus tincidunt nulla mollis ', 'Nobody', 'CargoPlane', 'Deconstructed', 179, '2000-09-10 21:29:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dignissim vestibulum vestibulu', 'EasyJet', 'Jet', 'Deconstructed', 63, '2014-09-22 13:01:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('turpis integer aliquet massa i', 'CroatiaAirlines', 'Airbus', 'OnRepair', 121, '2018-08-17 03:40:53');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ultrices libero non mattis pul', 'AirDump', 'Jet', 'Active', 172, '2002-10-18 23:55:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('et tempus semper est quam phar', 'Nobody', 'CargoPlane', 'OnRepair', 57, '2003-11-14 18:16:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('a ipsum integer a nibh in quis', 'Nobody', 'Jet', 'OnRepair', 151, '2002-06-20 03:23:37');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('in hac habitasse platea dictum', 'AirDump', 'Airbus', 'Deconstructed', 109, '2009-08-02 06:38:27');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quisque erat eros viverra eget', 'AirDump', 'Airbus', 'OnRepair', 137, '2019-11-20 11:00:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('praesent blandit nam nulla int', 'Nobody', 'CargoPlane', 'Deconstructed', 197, '2014-07-14 20:56:46');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mi sit amet lobortis sapien sa', 'Nobody', 'Jet', 'Deconstructed', 161, '2007-01-18 01:27:53');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lectus in est risus auctor sed', 'OnSale', 'CargoPlane', 'Active', 70, '2005-12-21 11:34:00');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('suscipit nulla elit ac nulla s', 'Nobody', 'CargoPlane', 'Deconstructed', 152, '2014-06-08 01:40:16');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('felis fusce posuere felis sed ', 'CroatiaAirlines', 'Airbus', 'Deconstructed', 141, '2007-05-23 00:37:42');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lacinia aenean sit amet justo ', 'CroatiaAirlines', 'Jet', 'OnRepair', 100, '2020-03-11 15:22:38');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eros vestibulum ac est lacinia', 'EasyJet', 'CargoPlane', 'Deconstructed', 139, '2009-05-11 02:06:41');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ipsum primis in faucibus orci ', 'EasyJet', 'Airbus', 'OnRepair', 172, '2013-04-03 20:41:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('congue eget semper rutrum null', 'Nobody', 'Jet', 'Active', 190, '2012-10-10 22:48:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('morbi sem mauris laoreet ut rh', 'EasyJet', 'CargoPlane', 'Active', 67, '2010-07-15 13:35:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('adipiscing lorem vitae mattis ', 'OnSale', 'CargoPlane', 'OnRepair', 125, '2014-03-12 20:19:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sed justo pellentesque viverra', 'AirDump', 'Jet', 'Active', 68, '2011-11-08 01:43:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('augue vestibulum ante ipsum pr', 'OnSale', 'Jet', 'Deconstructed', 155, '2014-06-07 00:18:50');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('diam cras pellentesque volutpa', 'EasyJet', 'Jet', 'OnRepair', 174, '2000-09-30 08:38:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('iaculis congue vivamus metus a', 'OnSale', 'CargoPlane', 'OnRepair', 133, '2011-10-26 16:50:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel pede morbi porttitor lorem', 'Nobody', 'CargoPlane', 'Active', 163, '2015-04-09 09:37:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('maecenas tincidunt lacus at ve', 'AirDump', 'Airbus', 'OnRepair', 133, '2018-12-06 08:19:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget congue eget semper rutrum', 'EasyJet', 'Jet', 'Deconstructed', 190, '2008-08-28 06:00:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('placerat praesent blandit nam ', 'CroatiaAirlines', 'Jet', 'Active', 134, '2006-09-28 06:00:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dui vel sem sed sagittis nam c', 'Nobody', 'CargoPlane', 'Active', 96, '2011-12-14 19:47:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id lobortis convallis tortor r', 'EasyJet', 'Jet', 'Deconstructed', 87, '2012-04-27 08:14:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu tincidunt in leo maecenas p', 'CroatiaAirlines', 'Jet', 'Deconstructed', 152, '2019-08-23 12:11:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('faucibus orci luctus et ultric', 'OnSale', 'CargoPlane', 'Deconstructed', 88, '2006-08-14 18:36:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nunc vestibulum ante ipsum pri', 'OnSale', 'CargoPlane', 'OnRepair', 188, '2003-04-20 07:04:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('a pede posuere nonummy integer', 'CroatiaAirlines', 'CargoPlane', 'OnRepair', 92, '2000-04-28 04:51:30');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dapibus augue vel accumsan tel', 'OnSale', 'Jet', 'Active', 55, '2011-11-04 21:15:16');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dictumst morbi vestibulum veli', 'Nobody', 'Airbus', 'OnRepair', 131, '2019-03-31 23:45:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('purus aliquet at feugiat non p', 'Nobody', 'Airbus', 'Active', 196, '2015-09-12 16:27:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('diam cras pellentesque volutpa', 'OnSale', 'Jet', 'OnRepair', 175, '2020-11-21 16:36:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vivamus tortor duis mattis ege', 'AirDump', 'Jet', 'Deconstructed', 173, '2006-02-03 02:46:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('a suscipit nulla elit ac nulla', 'OnSale', 'Airbus', 'Active', 80, '2008-04-04 10:30:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vitae mattis nibh ligula nec s', 'AirDump', 'CargoPlane', 'Deconstructed', 135, '2016-07-26 00:04:35');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit nec nisi vulputate nonum', 'OnSale', 'CargoPlane', 'Deconstructed', 104, '2014-05-25 13:10:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('donec odio justo sollicitudin ', 'Nobody', 'Jet', 'OnRepair', 63, '2004-12-26 10:52:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('placerat ante nulla justo aliq', 'OnSale', 'Airbus', 'Deconstructed', 89, '2004-03-03 00:34:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel pede morbi porttitor lorem', 'EasyJet', 'CargoPlane', 'Deconstructed', 111, '2020-07-14 03:46:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('risus praesent lectus vestibul', 'CroatiaAirlines', 'Jet', 'OnRepair', 146, '2016-09-01 06:22:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id ornare imperdiet sapien urn', 'OnSale', 'Jet', 'Deconstructed', 62, '2010-06-21 08:58:54');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('proin eu mi nulla ac enim in t', 'OnSale', 'Jet', 'Active', 177, '2021-01-05 23:06:29');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget nunc donec quis orci eget', 'AirDump', 'Airbus', 'Active', 149, '2007-09-28 12:07:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('a nibh in quis justo maecenas ', 'Nobody', 'Jet', 'OnRepair', 76, '2001-02-23 14:51:53');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('elementum nullam varius nulla ', 'OnSale', 'Airbus', 'OnRepair', 153, '2012-07-06 22:36:43');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eu mi nulla ac enim in tempor ', 'CroatiaAirlines', 'CargoPlane', 'Deconstructed', 199, '2003-01-24 17:20:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('magna at nunc commodo placerat', 'AirDump', 'CargoPlane', 'Deconstructed', 144, '2001-08-14 18:22:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('duis ac nibh fusce lacus purus', 'OnSale', 'Jet', 'Deconstructed', 171, '2020-12-29 09:35:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('duis aliquam convallis nunc pr', 'Nobody', 'CargoPlane', 'Active', 100, '2004-09-28 09:39:45');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quam a odio in hac habitasse p', 'EasyJet', 'Airbus', 'Active', 104, '2020-12-05 02:27:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('morbi sem mauris laoreet ut rh', 'EasyJet', 'Airbus', 'OnRepair', 108, '2010-01-02 10:48:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('consequat in consequat ut null', 'OnSale', 'Jet', 'Deconstructed', 152, '2011-04-15 21:50:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pede posuere nonummy integer n', 'Nobody', 'CargoPlane', 'Deconstructed', 65, '2002-10-26 14:22:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquam sit amet diam in magna', 'OnSale', 'Airbus', 'Active', 196, '2002-12-24 13:34:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('vel enim sit amet nunc viverra', 'EasyJet', 'CargoPlane', 'Deconstructed', 178, '2014-01-03 11:12:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('hac habitasse platea dictumst ', 'Nobody', 'CargoPlane', 'OnRepair', 175, '2001-08-25 11:41:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('primis in faucibus orci luctus', 'Nobody', 'Jet', 'Active', 110, '2014-12-02 23:18:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pede ac diam cras pellentesque', 'AirDump', 'Jet', 'Deconstructed', 108, '2000-06-28 01:29:11');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('tempus sit amet sem fusce cons', 'Nobody', 'CargoPlane', 'Deconstructed', 61, '2018-10-10 11:36:25');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sed vestibulum sit amet cursus', 'OnSale', 'Jet', 'Active', 75, '2007-03-26 01:23:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('congue diam id ornare imperdie', 'CroatiaAirlines', 'Airbus', 'OnRepair', 94, '2019-01-31 16:05:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aliquet massa id lobortis conv', 'Nobody', 'Airbus', 'OnRepair', 53, '2010-01-18 13:25:14');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('congue risus semper porta volu', 'Nobody', 'Airbus', 'Active', 108, '2012-09-15 03:46:11');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('consectetuer eget rutrum at lo', 'EasyJet', 'Airbus', 'OnRepair', 90, '2005-10-07 07:46:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget tempus vel pede morbi por', 'OnSale', 'Jet', 'Active', 180, '2020-08-03 23:54:18');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('est donec odio justo sollicitu', 'OnSale', 'CargoPlane', 'Deconstructed', 172, '2012-11-25 03:34:30');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget semper rutrum nulla nunc ', 'CroatiaAirlines', 'CargoPlane', 'OnRepair', 198, '2004-11-28 22:44:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('proin eu mi nulla ac enim in t', 'EasyJet', 'Jet', 'Deconstructed', 161, '2008-12-27 13:56:33');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('consectetuer adipiscing elit p', 'OnSale', 'CargoPlane', 'Deconstructed', 127, '2007-02-11 19:05:39');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nisi eu orci mauris lacinia sa', 'Nobody', 'Airbus', 'OnRepair', 73, '2004-12-23 05:55:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit eu est congue elementum ', 'EasyJet', 'Jet', 'Deconstructed', 55, '2014-08-07 18:25:22');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('fusce consequat nulla nisl nun', 'Nobody', 'Airbus', 'Deconstructed', 126, '2015-08-12 18:12:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('egestas metus aenean fermentum', 'OnSale', 'Jet', 'Deconstructed', 183, '2011-06-01 20:31:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sapien sapien non mi integer a', 'CroatiaAirlines', 'Airbus', 'OnRepair', 159, '2007-09-04 02:09:07');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla sed accumsan felis ut at', 'OnSale', 'Airbus', 'OnRepair', 53, '1999-08-21 07:36:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('rhoncus aliquet pulvinar sed n', 'Nobody', 'Airbus', 'Active', 166, '2014-02-08 06:22:38');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('risus semper porta volutpat qu', 'Nobody', 'CargoPlane', 'Deconstructed', 199, '2006-03-18 03:11:36');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nunc donec quis orci eget orci', 'Nobody', 'Jet', 'OnRepair', 176, '2009-04-05 02:06:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ac neque duis bibendum morbi n', 'EasyJet', 'CargoPlane', 'Deconstructed', 73, '2013-07-25 23:49:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sit amet sem fusce consequat n', 'EasyJet', 'CargoPlane', 'Deconstructed', 196, '2011-04-06 06:22:17');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit eu est congue elementum ', 'OnSale', 'CargoPlane', 'Deconstructed', 87, '2007-05-17 13:56:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('congue risus semper porta volu', 'CroatiaAirlines', 'Jet', 'OnRepair', 70, '2008-03-07 19:26:30');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('auctor sed tristique in tempus', 'OnSale', 'Jet', 'OnRepair', 186, '2012-04-28 06:42:31');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('montes nascetur ridiculus mus ', 'CroatiaAirlines', 'Jet', 'OnRepair', 189, '2010-10-01 09:10:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('id ligula suspendisse ornare c', 'AirDump', 'Airbus', 'OnRepair', 166, '2006-11-19 14:17:44');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('diam id ornare imperdiet sapie', 'Nobody', 'Jet', 'OnRepair', 68, '2003-05-22 00:50:23');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit nec nisi vulputate nonum', 'Nobody', 'Jet', 'Active', 171, '2008-01-06 14:25:12');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('pede venenatis non sodales sed', 'Nobody', 'Airbus', 'Deconstructed', 94, '2007-10-29 09:51:56');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('donec dapibus duis at velit eu', 'Nobody', 'Airbus', 'OnRepair', 157, '2017-12-10 13:40:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eget tincidunt eget tempus vel', 'Nobody', 'CargoPlane', 'OnRepair', 138, '2015-10-12 11:46:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('suspendisse potenti cras in pu', 'OnSale', 'CargoPlane', 'Active', 124, '2016-12-19 18:22:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('varius ut blandit non interdum', 'Nobody', 'Jet', 'OnRepair', 84, '2019-05-03 10:01:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('aenean fermentum donec ut maur', 'Nobody', 'CargoPlane', 'Deconstructed', 60, '2013-08-25 19:53:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ante ipsum primis in faucibus ', 'Nobody', 'Airbus', 'OnRepair', 52, '2018-12-21 00:48:56');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('quis libero nullam sit amet tu', 'EasyJet', 'CargoPlane', 'OnRepair', 198, '2014-05-20 11:26:32');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nascetur ridiculus mus etiam v', 'OnSale', 'CargoPlane', 'OnRepair', 87, '2019-05-08 00:55:40');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('potenti in eleifend quam a odi', 'CroatiaAirlines', 'CargoPlane', 'Active', 167, '2013-02-13 16:45:03');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dolor vel est donec odio justo', 'Nobody', 'CargoPlane', 'Active', 85, '2005-02-11 22:13:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('eros suspendisse accumsan tort', 'AirDump', 'CargoPlane', 'Active', 130, '2002-02-08 10:07:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('volutpat sapien arcu sed augue', 'Nobody', 'Jet', 'Active', 50, '2011-11-09 20:10:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut rhoncus aliquet pulvinar se', 'CroatiaAirlines', 'Airbus', 'Active', 157, '2004-09-08 08:00:28');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('neque sapien placerat ante nul', 'Nobody', 'Jet', 'Deconstructed', 136, '2004-04-11 05:15:19');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('a nibh in quis justo maecenas ', 'OnSale', 'CargoPlane', 'Active', 146, '2008-08-31 20:21:47');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nonummy integer non velit done', 'OnSale', 'Airbus', 'Active', 199, '2005-03-02 10:48:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sapien urna pretium nisl ut vo', 'Nobody', 'Jet', 'Active', 129, '2013-10-16 07:49:26');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('accumsan tellus nisi eu orci m', 'Nobody', 'Jet', 'Deconstructed', 63, '2012-12-28 01:30:49');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('nulla ac enim in tempor turpis', 'AirDump', 'Airbus', 'OnRepair', 200, '2007-12-22 11:52:01');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('volutpat dui maecenas tristiqu', 'Nobody', 'CargoPlane', 'Active', 197, '2002-05-14 07:57:05');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('odio elementum eu interdum eu ', 'Nobody', 'CargoPlane', 'Deconstructed', 199, '2013-12-16 06:46:30');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ut erat id mauris vulputate el', 'Nobody', 'CargoPlane', 'Deconstructed', 65, '2013-11-07 10:05:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ultrices phasellus id sapien i', 'OnSale', 'Airbus', 'Deconstructed', 77, '2010-09-02 20:21:06');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('velit nec nisi vulputate nonum', 'Nobody', 'Airbus', 'Deconstructed', 199, '2021-01-21 23:35:58');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('ante ipsum primis in faucibus ', 'Nobody', 'CargoPlane', 'Deconstructed', 145, '2016-06-06 16:34:28');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('odio justo sollicitudin ut sus', 'OnSale', 'Jet', 'Active', 92, '2016-03-16 08:07:38');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('facilisi cras non velit nec ni', 'Nobody', 'Airbus', 'Deconstructed', 146, '2012-02-23 11:42:52');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lacinia nisi venenatis tristiq', 'OnSale', 'CargoPlane', 'Deconstructed', 113, '2018-09-03 09:51:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('cum sociis natoque penatibus e', 'Nobody', 'CargoPlane', 'Deconstructed', 135, '2014-12-05 19:52:57');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('sapien ut nunc vestibulum ante', 'OnSale', 'CargoPlane', 'OnRepair', 73, '2013-09-06 11:42:51');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('libero nam dui proin leo odio ', 'OnSale', 'CargoPlane', 'OnRepair', 88, '2012-08-01 01:45:34');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('posuere felis sed lacus morbi ', 'OnSale', 'Airbus', 'Active', 174, '2011-06-29 14:17:55');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('amet lobortis sapien sapien no', 'OnSale', 'Airbus', 'OnRepair', 113, '2003-02-08 05:02:24');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('laoreet ut rhoncus aliquet pul', 'Nobody', 'CargoPlane', 'OnRepair', 132, '2015-12-15 21:29:09');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('adipiscing elit proin interdum', 'Nobody', 'Jet', 'Deconstructed', 131, '2004-05-28 17:07:21');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lectus aliquam sit amet diam i', 'EasyJet', 'CargoPlane', 'OnRepair', 146, '2004-08-24 00:15:13');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('leo odio porttitor id consequa', 'OnSale', 'Jet', 'Deconstructed', 170, '2006-07-21 12:06:43');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mauris morbi non lectus aliqua', 'EasyJet', 'Airbus', 'OnRepair', 79, '2003-09-17 03:09:20');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('mauris viverra diam vitae quam', 'OnSale', 'Airbus', 'Deconstructed', 66, '2016-06-29 06:16:59');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('neque duis bibendum morbi non ', 'OnSale', 'CargoPlane', 'OnRepair', 183, '2003-06-16 07:55:38');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('justo sit amet sapien dignissi', 'CroatiaAirlines', 'CargoPlane', 'Active', 191, '2013-06-26 06:04:30');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('lorem ipsum dolor sit amet con', 'OnSale', 'Airbus', 'Deconstructed', 122, '2000-09-06 06:41:16');
insert into Planes (Name, Company, Type, Activity, Capacity, DateOfCreation) values ('dictumst maecenas ut massa qui', 'OnSale', 'Airbus', 'OnRepair', 175, '2020-02-20 08:48:52');
